# Generated by Django 5.2.7 on 2025-12-09 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('openskagit', '0051_parcellidarstats'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AssessorWaterfacts',
            new_name='ParcelWaterfacts',
        ),
    ]
