# Generated by Django 5.2.7 on 2026-01-12 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openskagit', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyBriefingSendLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200)),
                ('sent_count', models.PositiveIntegerField(default=0)),
                ('error_count', models.PositiveIntegerField(default=0)),
                ('error_snapshot', models.TextField(blank=True)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='WeeklyBriefingTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(default='Weekly Briefing · OpenSkagit', max_length=200)),
                ('preheader', models.CharField(blank=True, default='County data, stories, and updates curated for you.', max_length=255)),
                ('hero_title', models.CharField(default='Skagit County by the numbers', max_length=200)),
                ('hero_lede', models.TextField(blank=True, default='Fresh data, approachable context, and stories that help Skagit neighborhoods move forward.')),
                ('hero_stat_label', models.CharField(blank=True, default='County updates', max_length=100)),
                ('hero_stat_value', models.CharField(blank=True, default='Up next', max_length=50)),
                ('cta_label', models.CharField(default='View the portal', max_length=100)),
                ('cta_url', models.URLField(blank=True, default='https://openskagit.com')),
                ('footer_note', models.TextField(blank=True, default='You are receiving this because you signed up for the OpenSkagit Weekly Briefing.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='WeeklyBriefingSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('summary', models.TextField(blank=True)),
                ('badge', models.CharField(blank=True, max_length=80)),
                ('highlight', models.CharField(blank=True, max_length=80)),
                ('order', models.PositiveIntegerField(default=0)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='openskagit.weeklybriefingtemplate')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
