# Generated by Codex on 2026-01-14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("openskagit", "0002_weeklybriefingsendlog_weeklybriefingtemplate_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AgencyFinancialSnapshot",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("mcag", models.CharField(db_index=True, max_length=10)),
                ("year", models.PositiveIntegerField(db_index=True)),
                ("name", models.CharField(max_length=255)),
                ("legal_name", models.CharField(blank=True, max_length=255)),
                ("gov_type_code", models.CharField(blank=True, max_length=4)),
                ("gov_type_desc", models.CharField(blank=True, max_length=100)),
                ("county_code", models.PositiveIntegerField(blank=True, null=True)),
                ("county_name", models.CharField(blank=True, max_length=100)),
                ("is_school", models.BooleanField(default=False)),
                (
                    "dataset_source",
                    models.CharField(
                        choices=[
                            ("ospi", "OSPI (School District portal)"),
                            ("snapshot31", "Snapshot 31 (Non-school governments)"),
                        ],
                        default="ospi",
                        max_length=32,
                    ),
                ),
                ("website", models.CharField(blank=True, max_length=255)),
                ("street_address", models.CharField(blank=True, max_length=255)),
                ("city", models.CharField(blank=True, max_length=120)),
                ("state", models.CharField(blank=True, max_length=2)),
                ("postal_code", models.CharField(blank=True, max_length=10)),
                ("latitude", models.FloatField(blank=True, null=True)),
                ("longitude", models.FloatField(blank=True, null=True)),
                ("fiscal_year_end", models.CharField(blank=True, max_length=20)),
                ("financial_summary", models.JSONField(blank=True, default=dict)),
                ("revenues", models.JSONField(blank=True, default=list)),
                ("expenditures", models.JSONField(blank=True, default=list)),
                ("indicators", models.JSONField(blank=True, default=list)),
                ("rankings", models.JSONField(blank=True, default=dict)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("raw_payloads", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["mcag", "-year"],
            },
        ),
        migrations.AddConstraint(
            model_name="agencyfinancialsnapshot",
            constraint=models.UniqueConstraint(
                fields=("mcag", "year"),
                name="uniq_agency_financial_snapshot",
            ),
        ),
    ]
