# Generated by Django 5.2.7 on 2025-10-12 17:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openskagit', '0002_assessor_improvements_land_sales_delete_authgroup_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CmaAnalysis',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('share_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('subject_parcel', models.CharField(max_length=32)),
                ('subject_snapshot', models.JSONField(blank=True, default=dict)),
                ('filters', models.JSONField(blank=True, default=dict)),
                ('manual_adjustments', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cma_analyses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='CmaComparableSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parcel_number', models.CharField(max_length=32)),
                ('included', models.BooleanField(default=True)),
                ('rank', models.PositiveIntegerField(default=0)),
                ('raw_sale_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('adjusted_sale_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('gross_percentage_adjustment', models.DecimalField(decimal_places=2, max_digits=6)),
                ('auto_adjustments', models.JSONField(blank=True, default=list)),
                ('manual_adjustments', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comparables', to='openskagit.cmaanalysis')),
            ],
            options={
                'ordering': ('rank',),
                'unique_together': {('analysis', 'parcel_number')},
            },
        ),
    ]
