# Generated by Django 5.2.7 on 2026-01-13 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openskagit', '0005_taxcodearea'),
    ]

    state_operations = [
        migrations.RenameIndex(
            model_name='taxcodearea',
            new_name='openskagit__tca_cod_221139_idx',
            old_name='openskagit_tca_year_idx',
        ),
        migrations.RenameIndex(
            model_name='taxcodeareadistrict',
            new_name='openskagit__tca_cod_bb0e6e_idx',
            old_name='openskagit_tcad_year_idx',
        ),
        migrations.RenameIndex(
            model_name='taxcodeareadistrict',
            new_name='openskagit__distric_96e335_idx',
            old_name='openskagit_tcad_dtype_idx',
        ),
        migrations.AlterField(
            model_name='taxcodearea',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='taxcodeareadistrict',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=state_operations,
        )
    ]
