# Generated by Django 5.2.7 on 2025-11-01 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openskagit', '0005_enable_trgm_and_address_trgm_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentRoll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(db_index=True)),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
