# Generated by Django 5.2.7 on 2025-11-01 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('openskagit', '0006_assessmentroll'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assessor',
            options={},
        ),
        migrations.AlterModelOptions(
            name='improvements',
            options={},
        ),
        migrations.AlterModelOptions(
            name='land',
            options={},
        ),
        migrations.AlterModelOptions(
            name='sales',
            options={},
        ),
    ]
