# Generated by Django 5.2.7 on 2025-11-01 23:46

import django.db.models.deletion
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openskagit', '0007_alter_assessor_options_alter_improvements_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assessor',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='improvements',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='land',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='sales',
            options={'managed': True},
        ),
        # migrations.AddField(
        #     model_name='assessor',
        #     name='embedding',
        #     field=pgvector.django.vector.VectorField(blank=True, dimensions=384, null=True),
        # ),
        migrations.AddField(
            model_name='assessor',
            name='roll',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assessors', to='openskagit.assessmentroll'),
        ),
        migrations.AddField(
            model_name='improvements',
            name='roll',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='improvements', to='openskagit.assessmentroll'),
        ),
        migrations.AddField(
            model_name='land',
            name='roll',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='land', to='openskagit.assessmentroll'),
        ),
        migrations.AddField(
            model_name='sales',
            name='roll',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='openskagit.assessmentroll'),
        ),
        migrations.AlterField(
            model_name='improvements',
            name='improvement_id',
            field=models.BigIntegerField(blank=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='improvements',
            name='parcel_number',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='land',
            name='land_segment_id',
            field=models.FloatField(blank=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='land',
            name='parcel_number',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='sales',
            name='parcel_number',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='sales',
            name='sale_id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterUniqueTogether(
            name='assessor',
            unique_together={('roll', 'parcel_number')},
        ),
    ]
