# Generated by Django 5.2.7 on 2026-01-14 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openskagit', '0007_merge_20240113_0000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxcodearea',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='taxcodeareadistrict',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='TaxingDistrictLevy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tdcode', models.CharField(db_index=True, help_text='Taxing District Code (TDCODE)', max_length=9)),
                ('district_name', models.CharField(help_text='District name from levy sheet', max_length=255)),
                ('locally_assessed_value', models.BigIntegerField(blank=True, null=True)),
                ('levy_rate', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True)),
                ('district_levy', models.BigIntegerField(blank=True, null=True)),
                ('highest_prior_levy', models.BigIntegerField(blank=True, null=True)),
                ('new_construction_assessed_value', models.BigIntegerField(blank=True, null=True)),
                ('levy_rate_2024', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True)),
                ('state_assessed_property_2024', models.BigIntegerField(blank=True, null=True)),
                ('state_assessed_property_2023', models.BigIntegerField(blank=True, null=True)),
                ('annexation_assessed_value_2023', models.BigIntegerField(blank=True, null=True)),
                ('annex_tax_due_2023', models.BigIntegerField(blank=True, null=True)),
                ('refund_tax_due_2023', models.BigIntegerField(blank=True, null=True)),
                ('max_allowable_levy', models.BigIntegerField(blank=True, null=True)),
                ('statutory_max_rate', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True)),
                ('levy_limit_percent_increase', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True)),
                ('assessment_year', models.PositiveSmallIntegerField(db_index=True, default=2024)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'taxing_district_levy',
                'indexes': [models.Index(fields=['tdcode'], name='taxing_dist_tdcode_60a920_idx'), models.Index(fields=['assessment_year'], name='taxing_dist_assessm_45e479_idx')],
                'unique_together': {('tdcode', 'assessment_year')},
            },
        ),
    ]
