# Generated by Django 5.2.7 on 2025-11-02 13:49

import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openskagit', '0008_alter_assessor_options_alter_improvements_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessor',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='improvements',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='land',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='sales',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='assessor',
            name='parcel_number',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='improvements',
            name='improvement_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='land',
            name='land_segment_id',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sales',
            name='sale_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
