# Generated by Django 5.2.7 on 2026-01-15 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openskagit', '0008_alter_taxcodearea_id_alter_taxcodeareadistrict_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parcelgeometry',
            name='flood_depth',
        ),
        migrations.RemoveField(
            model_name='parcelgeometry',
            name='flood_distance',
        ),
        migrations.RemoveField(
            model_name='parcelgeometry',
            name='flood_sfha',
        ),
        migrations.RemoveField(
            model_name='parcelgeometry',
            name='flood_static_bfe',
        ),
        migrations.RemoveField(
            model_name='parcelgeometry',
            name='flood_velocity',
        ),
        migrations.RemoveField(
            model_name='parcelgeometry',
            name='flood_zone',
        ),
        migrations.RemoveField(
            model_name='parcelgeometry',
            name='flood_zone_id',
        ),
        migrations.RemoveField(
            model_name='parcelgeometry',
            name='flood_zone_subtype',
        ),
        migrations.RemoveField(
            model_name='parcelgeometry',
            name='in_flood_zone',
        ),
        migrations.AddField(
            model_name='parcelplanningfacts',
            name='flood_depth',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parcelplanningfacts',
            name='flood_distance',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parcelplanningfacts',
            name='flood_sfha',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parcelplanningfacts',
            name='flood_static_bfe',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parcelplanningfacts',
            name='flood_velocity',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parcelplanningfacts',
            name='flood_zone',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parcelplanningfacts',
            name='flood_zone_id',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parcelplanningfacts',
            name='flood_zone_subtype',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parcelplanningfacts',
            name='in_flood_zone',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
