# Generated by Django 5.2.7 on 2025-11-02 17:53

import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openskagit', '0009_assessor_embedding_assessor_id_improvements_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parcel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parcel_number', models.CharField(db_index=True, max_length=20, unique=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('neighborhood_code', models.CharField(blank=True, db_index=True, max_length=10, null=True)),
                ('land_use_code', models.CharField(blank=True, db_index=True, max_length=10, null=True)),
                ('property_type', models.CharField(choices=[('R', 'Residential'), ('C', 'Commercial'), ('I', 'Industrial')], db_index=True, default='R', max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'parcel',
                'ordering': ['parcel_number'],
            },
        ),
    ]
