# Generated by Django 5.2.7 on 2026-01-16 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('openskagit', '0010_remove_planningfacts_duplicate_water_fields'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='parcelplanningfacts',
            name='parcel_plan_public__1b66b9_idx',
        ),
    ]
