# Generated by Django 5.2.7 on 2025-11-02 18:05

import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openskagit', '0010_parcel_assessor_embedding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcel',
            name='land_use_code',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='neighborhood_code',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
    ]
