# Generated by Django 5.2.7 on 2025-11-03 15:05

import django.db.models.deletion
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openskagit', '0011_assessor_embedding_alter_parcel_land_use_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegressionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_type', models.CharField(default='log_linear', max_length=50)),
                ('run_date', models.DateTimeField(auto_now_add=True)),
                ('n_obs', models.IntegerField()),
                ('r_squared', models.FloatField()),
                ('adj_r_squared', models.FloatField()),
                ('coefficients', models.JSONField()),
                ('notes', models.TextField(blank=True)),
                ('roll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='openskagit.assessmentroll')),
            ],
            options={
                'db_table': 'regression_results',
                'ordering': ['-run_date'],
            },
        ),
    ]
