# Generated by Django 5.2.7 on 2025-11-04 17:56

import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openskagit', '0013_regressionadjustment_assessor_embedding'),
    ]

    operations = [
        migrations.CreateModel(
            name='NeighborhoodMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('neighborhood_code', models.CharField(db_index=True, max_length=20)),
                ('year', models.IntegerField()),
                ('sales_ratio', models.FloatField(null=True)),
                ('median_ratio', models.FloatField(null=True)),
                ('cod', models.FloatField(null=True)),
                ('prd', models.FloatField(null=True)),
                ('sample_size', models.IntegerField(default=0)),
                ('reliability', models.CharField(blank=True, max_length=20)),
                ('computed_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
