# Generated by Django 5.2.7 on 2026-01-16 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('openskagit', '0014_add_assessor_owner_fields'),
    ]

    operations = []
