# Generated by Django 5.2.7 on 2025-11-04 19:26

import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openskagit', '0014_neighborhoodmetrics_assessor_embedding'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessor',
            name='land_use_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assessor',
            name='neighborhood_code_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
