# Generated by Django 5.2.7 on 2025-11-14 23:00

import django.contrib.gis.db.models.fields
import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('openskagit', '0015_assessor_embedding_assessor_land_use_description_and_more'),
    ]

    operations = [
    migrations.RunSQL("-- centroid_geog already exists"),
]
