# Generated by Django 5.2.7 on 2026-01-18 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("openskagit", "0015_rename_assessor_wa_public__72bad9_idx_openskagit__public__2044ad_idx_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="parcelplanningfacts",
            name="airport_environs_zone",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
