# Generated by Django 5.2.7 on 2026-01-19 21:39

import django.contrib.gis.db.models.fields
import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openskagit', '0016_alter_parcelplanningfacts_airport_environs_zone_length'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='parcelwaterfacts',
            new_name='openskagit__public__2044ad_idx',
            old_name='assessor_wa_public__72bad9_idx',
        ),
        migrations.RenameIndex(
            model_name='parcelwaterfacts',
            new_name='openskagit__has_pou_81a6b2_idx',
            old_name='assessor_wa_has_pou_af6d64_idx',
        ),
        migrations.AddField(
            model_name='parcelgeometry',
            name='centroid_2926',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=2926),
        ),
        migrations.AddField(
            model_name='parcelplanningfacts',
            name='zone_id',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='parcelgeometry',
            index=django.contrib.postgres.indexes.GistIndex(fields=['centroid_2926'], name='openskagit__centroi_4fae49_gist'),
        ),
        migrations.AlterModelTable(
            name='parcelwaterfacts',
            table='openskagit_parcelwaterfacts',
        ),
    ]
