# Generated by Django 5.2.7 on 2026-01-21 17:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openskagit', '0017_rename_assessor_wa_public__72bad9_idx_openskagit__public__2044ad_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParcelIntent',
            fields=[
                ('key', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('triggers_law_classes', models.JSONField(default=list)),
                ('external_authorities', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PermitType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('category', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='PermitTypeIntentMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='openskagit.parcelintent')),
                ('permit_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='openskagit.permittype')),
            ],
            options={
                'unique_together': {('permit_type', 'intent')},
            },
        ),
    ]
