# Generated by Django 5.2.7 on 2025-11-17 17:47

import django.contrib.gis.db.models.fields
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openskagit', '0017_parcel_autocomplete_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdjustmentCoefficient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('market_group', models.CharField(db_index=True, max_length=100)),
                ('term', models.CharField(db_index=True, max_length=200)),
                ('beta', models.FloatField()),
                ('beta_se', models.FloatField(blank=True, null=True)),
                ('run_id', models.CharField(db_index=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['market_group', 'term'], name='openskagit__market__5e467b_idx')],
                'unique_together': {('market_group', 'term', 'run_id')},
            },
        ),
    ]
