# Generated by Django 5.2.7 on 2025-11-18 17:28

import django.contrib.gis.db.models.fields
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openskagit', '0018_assessor_centroid_geog_assessor_embedding_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NeighborhoodGeom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=20, unique=True)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('geom_3857', django.contrib.gis.db.models.fields.MultiPolygonField(srid=3857)),
                ('geom_4326', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
        ),
    ]
