# Generated by Django 5.2.7 on 2026-01-21 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openskagit', '0018_parcelintent_permittype_permittypeintentmap'),
    ]

    operations = [
        migrations.CreateModel(
            name='JurisdictionCodeSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jurisdiction_key', models.CharField(max_length=50)),
                ('code_set', models.CharField(max_length=100)),
                ('source', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'db_table': 'jurisdiction_code_set',
                'unique_together': {('jurisdiction_key', 'code_set')},
            },
        ),
    ]
