# Generated by Django 5.2.7 on 2026-01-21 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openskagit', '0019_jurisdictioncodeset'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeSetActivationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_set', models.CharField(max_length=100)),
                ('parcel_intent', models.CharField(blank=True, max_length=100, null=True)),
                ('zoning_use_class', models.CharField(blank=True, max_length=50, null=True)),
                ('requires_overlay', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'code_set_activation_rule',
            },
        ),
    ]
