# Generated by Django 5.2.7 on 2025-11-18 18:41

import django.contrib.gis.db.models.fields
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openskagit', '0019_neighborhoodgeom_assessor_centroid_geog_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NeighborhoodProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hood_id', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('json_data', models.JSONField(default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
