# Generated by Django 5.2.7 on 2025-11-19 13:04

import django.contrib.gis.db.models.fields
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openskagit', '0020_neighborhoodprofile_assessor_centroid_geog_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='neighborhoodprofile',
            name='ai_summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
