# Generated by Django 5.2.7 on 2025-11-19 22:09

import django.contrib.gis.db.models.fields
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openskagit', '0021_assessor_centroid_geog_assessor_embedding_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParcelHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parcel_number', models.CharField(max_length=20, unique=True)),
                ('rows', models.JSONField(default=list)),
                ('scraped_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
