# Generated by Django 5.2.7 on 2026-02-13 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openskagit', '0022_parcelhistory_taxes'),
    ]

    operations = [
        migrations.CreateModel(
            name='SedroWoolleyCrawlDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(db_index=True, max_length=1000)),
                ('url_hash', models.CharField(db_index=True, max_length=64)),
                ('source_url', models.URLField(blank=True, max_length=1000, null=True)),
                ('depth', models.PositiveIntegerField(default=0)),
                ('resource_type', models.CharField(max_length=32)),
                ('title', models.CharField(blank=True, max_length=500)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('status_code', models.PositiveIntegerField(blank=True, null=True)),
                ('content_type', models.CharField(blank=True, max_length=255)),
                ('extension', models.CharField(blank=True, max_length=20)),
                ('size_bytes', models.BigIntegerField(default=0)),
                ('sha256', models.CharField(blank=True, max_length=64)),
                ('fetched_at', models.DateTimeField()),
                ('media_path', models.CharField(blank=True, max_length=800)),
                ('raw_html_path', models.CharField(blank=True, max_length=800)),
                ('text_path', models.CharField(blank=True, max_length=800)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-fetched_at'],
            },
        ),
        migrations.CreateModel(
            name='SedroWoolleyCrawlRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_id', models.CharField(db_index=True, max_length=32, unique=True)),
                ('start_url', models.URLField(max_length=1000)),
                ('allowed_domains', models.JSONField(blank=True, default=list)),
                ('max_depth', models.PositiveIntegerField(default=0)),
                ('max_pages', models.PositiveIntegerField(default=0)),
                ('resumed', models.BooleanField(default=False)),
                ('dry_run', models.BooleanField(default=False)),
                ('started_at', models.DateTimeField()),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.FloatField(blank=True, null=True)),
                ('urls_processed', models.PositiveIntegerField(default=0)),
                ('urls_seen', models.PositiveIntegerField(default=0)),
                ('records_written', models.PositiveIntegerField(default=0)),
                ('html_pages', models.PositiveIntegerField(default=0)),
                ('files', models.PositiveIntegerField(default=0)),
                ('failure_count', models.PositiveIntegerField(default=0)),
                ('by_resource_type', models.JSONField(blank=True, default=dict)),
                ('by_extension', models.JSONField(blank=True, default=dict)),
                ('tag_counts', models.JSONField(blank=True, default=dict)),
                ('failures', models.JSONField(blank=True, default=list)),
                ('manifest_path', models.CharField(blank=True, max_length=500)),
                ('run_summary_path', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.AddIndex(
            model_name='sedrowoolleycrawlrun',
            index=models.Index(fields=['-started_at'], name='openskagit__started_31ebe9_idx'),
        ),
        migrations.AddIndex(
            model_name='sedrowoolleycrawlrun',
            index=models.Index(fields=['dry_run', '-started_at'], name='openskagit__dry_run_655f09_idx'),
        ),
        migrations.AddField(
            model_name='sedrowoolleycrawldocument',
            name='run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='openskagit.sedrowoolleycrawlrun'),
        ),
        migrations.AddIndex(
            model_name='sedrowoolleycrawldocument',
            index=models.Index(fields=['run', '-fetched_at'], name='openskagit__run_id_330c15_idx'),
        ),
        migrations.AddIndex(
            model_name='sedrowoolleycrawldocument',
            index=models.Index(fields=['resource_type'], name='openskagit__resourc_e58c6b_idx'),
        ),
        migrations.AddIndex(
            model_name='sedrowoolleycrawldocument',
            index=models.Index(fields=['extension'], name='openskagit__extensi_f38ec3_idx'),
        ),
        migrations.AddConstraint(
            model_name='sedrowoolleycrawldocument',
            constraint=models.UniqueConstraint(fields=('run', 'url_hash'), name='uniq_sw_crawl_doc_run_urlhash'),
        ),
    ]
