# Generated by Django 5.2.7

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("openskagit", "0022_parcelhistory_assessor_centroid_geog_and_more"),
    ]

    operations = [
        migrations.RunSQL(
            "ALTER TABLE assessor DROP COLUMN IF EXISTS geom_4326;",
            reverse_sql=(
                "ALTER TABLE assessor "
                "ADD COLUMN geom_4326 geometry(Geometry, 4326) "
                "GENERATED ALWAYS AS (st_transform(geom, 4326)) STORED;"
            ),
        ),
        migrations.AlterField(
            model_name="assessor",
            name="geom",
            field=django.contrib.gis.db.models.fields.MultiPolygonField(
                blank=True,
                null=True,
                srid=3857,
            ),
        ),
        migrations.RunSQL(
            (
                "ALTER TABLE assessor "
                "ADD COLUMN geom_4326 geometry(MULTIPOLYGON, 4326) "
                "GENERATED ALWAYS AS (st_transform(geom, 4326)) STORED;"
            ),
            reverse_sql="ALTER TABLE assessor DROP COLUMN IF EXISTS geom_4326;",
        ),
    ]
