# Generated by Django 5.2.7 on 2025-11-21 14:52

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import pgvector.django.vector
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openskagit', '0023_assessor_geom_multipolygon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_key', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('title', models.CharField(default='New conversation', max_length=255)),
                ('context_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'conversations',
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['-updated_at'], name='conversatio_updated_c163ba_idx'), models.Index(fields=['session_key', '-updated_at'], name='conversatio_session_69f832_idx')],
            },
        ),
        migrations.CreateModel(
            name='NeighborhoodTrend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hood_id', models.CharField(db_index=True, max_length=20)),
                ('value_year', models.IntegerField(db_index=True)),
                ('median_land_market', models.IntegerField(blank=True, null=True)),
                ('median_building', models.IntegerField(blank=True, null=True)),
                ('median_market_total', models.IntegerField(blank=True, null=True)),
                ('median_tax_amount', models.IntegerField(blank=True, null=True)),
                ('yoy_change_land', models.FloatField(blank=True, null=True)),
                ('yoy_change_building', models.FloatField(blank=True, null=True)),
                ('yoy_change_total', models.FloatField(blank=True, null=True)),
                ('yoy_change_tax', models.FloatField(blank=True, null=True)),
                ('stability_score', models.FloatField(blank=True, null=True)),
                ('boom_bust_flag', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['hood_id', 'value_year'], name='openskagit__hood_id_52cf7e_idx')],
                'unique_together': {('hood_id', 'value_year')},
            },
        ),
        migrations.CreateModel(
            name='ConversationMessage',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant'), ('system', 'System')], max_length=20)),
                ('content', models.TextField()),
                ('sources', models.JSONField(blank=True, default=list)),
                ('model', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='openskagit.conversation')),
            ],
            options={
                'db_table': 'conversation_messages',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['conversation', 'created_at'], name='conversatio_convers_01af31_idx')],
            },
        ),
    ]
