# Generated by Django 5.2.7 on 2026-02-13 19:36

import django.db.models.deletion
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("openskagit", "0023_sedro_woolley_crawl_models"),
    ]

    operations = [
        migrations.CreateModel(
            name="SedroWoolleyYoutubeVideo",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("video_id", models.CharField(db_index=True, max_length=32, unique=True)),
                ("video_url", models.URLField(max_length=1000, unique=True)),
                ("channel_url", models.URLField(blank=True, max_length=1000)),
                ("channel_id", models.CharField(blank=True, max_length=128)),
                ("channel_title", models.CharField(blank=True, max_length=500)),
                ("title", models.CharField(blank=True, max_length=500)),
                ("description", models.TextField(blank=True)),
                ("upload_date", models.DateField(blank=True, null=True)),
                ("duration_seconds", models.PositiveIntegerField(blank=True, null=True)),
                ("transcript_language", models.CharField(blank=True, max_length=20)),
                ("transcript_segment_count", models.PositiveIntegerField(default=0)),
                ("transcript_char_count", models.PositiveIntegerField(default=0)),
                ("chunk_count", models.PositiveIntegerField(default=0)),
                ("whisper_model", models.CharField(blank=True, max_length=100)),
                ("embedding_model", models.CharField(blank=True, max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("skipped", "Skipped"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("failure_count", models.PositiveIntegerField(default=0)),
                ("last_error", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("last_seen_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-upload_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SedroWoolleyYoutubeChunk",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "video",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chunks",
                        to="openskagit.sedrowoolleyyoutubevideo",
                    ),
                ),
                ("chunk_index", models.PositiveIntegerField(default=0)),
                ("chunk_text", models.TextField()),
                ("start_time", models.FloatField(default=0)),
                ("end_time", models.FloatField(default=0)),
                ("token_count", models.PositiveIntegerField(default=0)),
                ("content_hash", models.CharField(db_index=True, max_length=64)),
                ("embedding_model", models.CharField(max_length=100)),
                ("embedding", pgvector.django.vector.VectorField(blank=True, dimensions=384, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddIndex(
            model_name="sedrowoolleyyoutubevideo",
            index=models.Index(fields=["status", "-updated_at"], name="openskagit__status_ac5919_idx"),
        ),
        migrations.AddIndex(
            model_name="sedrowoolleyyoutubevideo",
            index=models.Index(fields=["channel_id", "-upload_date"], name="openskagit__channel_7fd826_idx"),
        ),
        migrations.AddIndex(
            model_name="sedrowoolleyyoutubevideo",
            index=models.Index(fields=["-upload_date"], name="openskagit__upload__4124a6_idx"),
        ),
        migrations.AddIndex(
            model_name="sedrowoolleyyoutubechunk",
            index=models.Index(fields=["video", "chunk_index"], name="openskagit__video_i_9ae50a_idx"),
        ),
        migrations.AddIndex(
            model_name="sedrowoolleyyoutubechunk",
            index=models.Index(fields=["embedding_model"], name="openskagit__embeddi_c6ba58_idx"),
        ),
        migrations.AddConstraint(
            model_name="sedrowoolleyyoutubechunk",
            constraint=models.UniqueConstraint(
                fields=("video", "chunk_index", "embedding_model"),
                name="uniq_sw_youtube_chunk_video_model_idx",
            ),
        ),
    ]
