# Generated by Django 5.2.7 on 2026-02-19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("openskagit", "0024_sedrowoolleyyoutubechunk_sedrowoolleyyoutubevideo_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RegressionPublishedModel",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("mode", models.CharField(db_index=True, default="sfr", max_length=50)),
                ("run_id", models.CharField(db_index=True, max_length=100)),
                ("settings_json", models.JSONField(default=dict)),
                ("coefficients_json", models.JSONField(default=list)),
                ("segments_json", models.JSONField(default=list)),
                ("global_metrics_json", models.JSONField(default=dict)),
                ("segment_map_json", models.JSONField(default=list)),
                ("is_active", models.BooleanField(db_index=True, default=False)),
                ("promoted_at", models.DateTimeField(blank=True, null=True)),
                ("diagnostics_path", models.CharField(blank=True, max_length=500)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "promoted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="regression_published_models",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["mode", "is_active"], name="openskagit__mode_7f8c4f_idx"),
                    models.Index(fields=["run_id"], name="openskagit__run_id_9e4a1d_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("is_active", True)),
                        fields=("mode",),
                        name="openskagit_regpub_unique_active_mode",
                    )
                ],
            },
        ),
    ]
