# Generated by Django 5.2.7 on 2025-11-21 15:23

import django.contrib.gis.db.models.fields
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openskagit', '0024_assessor_centroid_geog_assessor_embedding_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcelhistory',
            name='neighborhood_code',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='parcelhistory',
            name='roll_year',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
    ]
