# Generated by Django 5.2.7 on 2026-02-20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("openskagit", "0025_regressionpublishedmodel"),
    ]

    operations = [
        migrations.CreateModel(
            name="SedroWoolleyPermit",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("external_id", models.CharField(db_index=True, max_length=32, unique=True)),
                ("detail_url", models.URLField(max_length=1000)),
                ("source_list_url", models.URLField(blank=True, max_length=1000)),
                ("permit_number", models.CharField(blank=True, db_index=True, max_length=64)),
                ("permit_date", models.DateField(blank=True, db_index=True, null=True)),
                ("primary_contractor", models.CharField(blank=True, max_length=255)),
                ("permit_type", models.CharField(blank=True, db_index=True, max_length=255)),
                ("site_address", models.CharField(blank=True, max_length=500)),
                ("work_description", models.TextField(blank=True)),
                ("status", models.CharField(blank=True, db_index=True, max_length=120)),
                ("parcel_number", models.CharField(blank=True, db_index=True, max_length=64)),
                ("property_address", models.CharField(blank=True, max_length=500)),
                ("property_city", models.CharField(blank=True, max_length=120)),
                ("property_state", models.CharField(blank=True, max_length=20)),
                ("property_postal_code", models.CharField(blank=True, max_length=20)),
                ("owner_name", models.CharField(blank=True, max_length=255)),
                ("owner_address", models.CharField(blank=True, max_length=500)),
                ("owner_city", models.CharField(blank=True, max_length=120)),
                ("owner_state", models.CharField(blank=True, max_length=20)),
                ("owner_postal_code", models.CharField(blank=True, max_length=20)),
                ("total_fees", models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ("amount_due", models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ("notes_text", models.TextField(blank=True)),
                ("uploaded_file_count", models.PositiveIntegerField(default=0)),
                ("source_start_date", models.DateField(blank=True, null=True)),
                ("source_end_date", models.DateField(blank=True, null=True)),
                ("content_hash", models.CharField(db_index=True, max_length=64)),
                ("raw_payload", models.JSONField(blank=True, default=dict)),
                ("first_seen_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("last_seen_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("last_changed_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("last_crawled_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-permit_date", "-updated_at"],
                "indexes": [
                    models.Index(fields=["-permit_date"], name="sw_permit_date_desc_idx"),
                    models.Index(fields=["status", "permit_type"], name="sw_permit_status_type_idx"),
                    models.Index(fields=["parcel_number", "-permit_date"], name="sw_permit_parcel_date_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="SedroWoolleyPermitSyncRun",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("run_id", models.CharField(db_index=True, max_length=40, unique=True)),
                (
                    "mode",
                    models.CharField(
                        choices=[("backfill", "Backfill"), ("sync", "Sync")],
                        db_index=True,
                        default="sync",
                        max_length=20,
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("chunk_months", models.PositiveIntegerField(default=0)),
                ("dry_run", models.BooleanField(default=False)),
                ("started_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("duration_seconds", models.FloatField(blank=True, null=True)),
                ("list_pages_fetched", models.PositiveIntegerField(default=0)),
                ("detail_pages_fetched", models.PositiveIntegerField(default=0)),
                ("permits_seen", models.PositiveIntegerField(default=0)),
                ("permits_new", models.PositiveIntegerField(default=0)),
                ("permits_updated", models.PositiveIntegerField(default=0)),
                ("permits_unchanged", models.PositiveIntegerField(default=0)),
                ("permit_failures", models.PositiveIntegerField(default=0)),
                ("failures", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-started_at"],
                "indexes": [
                    models.Index(fields=["mode", "-started_at"], name="sw_permit_run_mode_started_idx"),
                    models.Index(fields=["start_date", "end_date"], name="sw_permit_run_range_idx"),
                ],
            },
        ),
    ]
