# Generated by Django 5.2.7 on 2025-11-21 17:23

import django.contrib.gis.db.models.fields
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openskagit', '0025_assessor_centroid_geog_assessor_embedding_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcel',
            name='neighborhood_description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
