# Generated by Django 5.2.7 on 2025-11-21 23:09

import django.contrib.gis.db.models.fields
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openskagit', '0027_comparablecache'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessor',
            name='condition_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='assessor',
            name='condition_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assessor',
            name='quality_score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
