# Generated by Django 5.2.7 on 2026-02-20 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openskagit', '0027_sedrowoolleypermit_llm_classifications'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='agencylevymap',
            new_name='agency_levy_tdcode_33f77d_idx',
            old_name='openskagit_agencylevymap_tdcode_idx',
        ),
        migrations.RenameIndex(
            model_name='agencylevymap',
            new_name='agency_levy_mcag_ba8cec_idx',
            old_name='openskagit_agencylevymap_mcag_idx',
        ),
        migrations.RenameIndex(
            model_name='regressionpublishedmodel',
            new_name='openskagit__mode_1e7390_idx',
            old_name='openskagit__mode_7f8c4f_idx',
        ),
        migrations.RenameIndex(
            model_name='regressionpublishedmodel',
            new_name='openskagit__run_id_5866ab_idx',
            old_name='openskagit__run_id_9e4a1d_idx',
        ),
        migrations.RenameIndex(
            model_name='sedrowoolleypermit',
            new_name='openskagit__permit__3506f7_idx',
            old_name='sw_permit_date_desc_idx',
        ),
        migrations.RenameIndex(
            model_name='sedrowoolleypermit',
            new_name='openskagit__status_fc3999_idx',
            old_name='sw_permit_status_type_idx',
        ),
        migrations.RenameIndex(
            model_name='sedrowoolleypermit',
            new_name='openskagit__parcel__c0c34c_idx',
            old_name='sw_permit_parcel_date_idx',
        ),
        migrations.RenameIndex(
            model_name='sedrowoolleypermitsyncrun',
            new_name='openskagit__mode_ddfe87_idx',
            old_name='sw_permit_run_mode_started_idx',
        ),
        migrations.RenameIndex(
            model_name='sedrowoolleypermitsyncrun',
            new_name='openskagit__start_d_490ee3_idx',
            old_name='sw_permit_run_range_idx',
        ),
        migrations.AlterField(
            model_name='agencylevymap',
            name='mcag',
            field=models.CharField(blank=True, db_index=True, default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='contactsubmission',
            name='topic',
            field=models.CharField(choices=[('support', 'Support & product help'), ('partnership', 'Partnership or collaboration'), ('media', 'Press or media request'), ('data', 'Data or research question'), ('consulting', 'Consulting & workflow help')], default='support', max_length=32),
        ),
    ]
