# Generated by Django 5.2.7 on 2025-11-24 15:14

import django.contrib.gis.db.models.fields
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openskagit', '0028_rename_openskagit_compcache_parcel_roll_idx_comparable__parcel__84e718_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdjustmentRunSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_id', models.CharField(db_index=True, max_length=20, unique=True)),
                ('stats', models.JSONField(help_text='List of per-market diagnostic rows for this run.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RenameIndex(
            model_name='comparablecache',
            new_name='comparable__parcel__84e718_idx',
            old_name='openskagit_compcache_parcel_roll_idx',
        ),
    ]
