# Generated by Django 5.2.7 on 2026-02-20 22:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openskagit', '0028_rename_openskagit_agencylevymap_tdcode_idx_agency_levy_tdcode_33f77d_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParcelOwner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_name', models.TextField(blank=True, null=True)),
                ('owner_add_1', models.TextField(blank=True, null=True)),
                ('owner_add_2', models.TextField(blank=True, null=True)),
                ('owner_add_3', models.TextField(blank=True, null=True)),
                ('owner_city', models.TextField(blank=True, null=True)),
                ('owner_state', models.TextField(blank=True, null=True)),
                ('owner_zip', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parcel', models.OneToOneField(db_column='parcel_id', on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='openskagit.masterparcel')),
                ('source_assessor', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parcel_owners', to='openskagit.assessor')),
                ('source_roll', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parcel_owners', to='openskagit.assessmentroll')),
            ],
            options={
                'db_table': 'parcel_owner',
                'indexes': [models.Index(fields=['owner_name'], name='parcel_owne_owner_n_425b68_idx'), models.Index(fields=['owner_city', 'owner_state'], name='parcel_owne_owner_c_33ca67_idx'), models.Index(fields=['source_roll'], name='parcel_owne_source__bc084c_idx')],
            },
        ),
    ]
