# Generated by Django 5.2.7 on 2025-11-24 17:55

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openskagit', '0029_adjustmentrunsummary_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdjustmentModelSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('market_group', models.CharField(max_length=100)),
                ('value_tier', models.CharField(max_length=20)),
                ('price_min', models.FloatField(help_text='Lower bound of sales used in this model')),
                ('price_max', models.FloatField(help_text='Upper bound of sales used in this model')),
                ('n_obs', models.IntegerField(help_text='Number of sales in this tier')),
                ('r2', models.FloatField(null=True)),
                ('cod', models.FloatField(help_text='Coefficient of Dispersion', null=True)),
                ('prd', models.FloatField(help_text='Price Related Differential', null=True)),
                ('median_ratio', models.FloatField(null=True)),
                ('included_predictors', models.JSONField(default=list)),
            ],
            options={
                'ordering': ['market_group', 'value_tier'],
            },
        ),
        migrations.AlterModelOptions(
            name='adjustmentrunsummary',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='adjustmentcoefficient',
            name='openskagit__market__5e467b_idx',
        ),
        migrations.RemoveField(
            model_name='adjustmentrunsummary',
            name='stats',
        ),
        migrations.AddField(
            model_name='adjustmentmodelsegment',
            name='run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='openskagit.adjustmentrunsummary'),
        ),
        migrations.AlterUniqueTogether(
            name='adjustmentmodelsegment',
            unique_together={('run', 'market_group', 'value_tier')},
        ),
    ]
