# Generated by Django 5.2.7 on 2026-02-20 22:58

import django.db.models.deletion
from django.db import migrations, models


def _backfill_sedro_woolley_permit_links(apps, schema_editor):
    Permit = apps.get_model("openskagit", "SedroWoolleyPermit")
    MasterParcel = apps.get_model("openskagit", "MasterParcel")
    ParcelOwner = apps.get_model("openskagit", "ParcelOwner")

    parcel_numbers = {
        parcel.strip()
        for parcel in Permit.objects.exclude(parcel_number__isnull=True)
        .exclude(parcel_number="")
        .values_list("parcel_number", flat=True)
        if parcel and parcel.strip()
    }
    if not parcel_numbers:
        return

    valid_parcels = set(
        MasterParcel.objects.filter(parcel_number__in=parcel_numbers).values_list("parcel_number", flat=True)
    )
    if not valid_parcels:
        return

    owner_by_parcel = dict(
        ParcelOwner.objects.filter(parcel_id__in=valid_parcels).values_list("parcel_id", "id")
    )

    updates = []
    qs = (
        Permit.objects.exclude(parcel_number__isnull=True)
        .exclude(parcel_number="")
        .only("id", "parcel_number", "parcel_id", "owner_id")
    )
    for permit in qs.iterator(chunk_size=1000):
        parcel_number = (permit.parcel_number or "").strip()
        if not parcel_number or parcel_number not in valid_parcels:
            continue
        permit.parcel_id = parcel_number
        permit.owner_id = owner_by_parcel.get(parcel_number)
        updates.append(permit)
        if len(updates) >= 1000:
            Permit.objects.bulk_update(updates, ["parcel", "owner"], batch_size=1000)
            updates = []

    if updates:
        Permit.objects.bulk_update(updates, ["parcel", "owner"], batch_size=1000)


def _noop_reverse(apps, schema_editor):
    return


class Migration(migrations.Migration):

    dependencies = [
        ('openskagit', '0029_parcelowner'),
    ]

    operations = [
        migrations.AddField(
            model_name='sedrowoolleypermit',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sedro_woolley_permits', to='openskagit.parcelowner'),
        ),
        migrations.AddField(
            model_name='sedrowoolleypermit',
            name='parcel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sedro_woolley_permits', to='openskagit.masterparcel'),
        ),
        migrations.RunPython(
            _backfill_sedro_woolley_permit_links,
            _noop_reverse,
        ),
        migrations.RemoveIndex(
            model_name='sedrowoolleypermit',
            name='openskagit__parcel__c0c34c_idx',
        ),
        migrations.RemoveField(
            model_name='sedrowoolleypermit',
            name='first_seen_at',
        ),
        migrations.RemoveField(
            model_name='sedrowoolleypermit',
            name='last_changed_at',
        ),
        migrations.RemoveField(
            model_name='sedrowoolleypermit',
            name='last_crawled_at',
        ),
        migrations.RemoveField(
            model_name='sedrowoolleypermit',
            name='last_seen_at',
        ),
        migrations.RemoveField(
            model_name='sedrowoolleypermit',
            name='owner_address',
        ),
        migrations.RemoveField(
            model_name='sedrowoolleypermit',
            name='owner_city',
        ),
        migrations.RemoveField(
            model_name='sedrowoolleypermit',
            name='owner_name',
        ),
        migrations.RemoveField(
            model_name='sedrowoolleypermit',
            name='owner_postal_code',
        ),
        migrations.RemoveField(
            model_name='sedrowoolleypermit',
            name='owner_state',
        ),
        migrations.RemoveField(
            model_name='sedrowoolleypermit',
            name='parcel_number',
        ),
        migrations.RemoveField(
            model_name='sedrowoolleypermit',
            name='property_address',
        ),
        migrations.RemoveField(
            model_name='sedrowoolleypermit',
            name='property_city',
        ),
        migrations.RemoveField(
            model_name='sedrowoolleypermit',
            name='property_postal_code',
        ),
        migrations.RemoveField(
            model_name='sedrowoolleypermit',
            name='property_state',
        ),
        migrations.AddIndex(
            model_name='sedrowoolleypermit',
            index=models.Index(fields=['parcel', '-permit_date'], name='openskagit__parcel__e3471e_idx'),
        ),
    ]
