# Generated by Django 5.2.7 on 2026-02-25

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("openskagit", "0030_remove_sedrowoolleypermit_openskagit__parcel__c0c34c_idx_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SedroWoolleyPermitAlertRun",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("run_id", models.CharField(db_index=True, max_length=40, unique=True)),
                ("job_name", models.CharField(db_index=True, default="nightly_sw_permit_alert", max_length=50)),
                ("dry_run", models.BooleanField(default=False)),
                ("sync_attempted", models.BooleanField(default=True)),
                ("watermark_from", models.DateTimeField(blank=True, null=True)),
                ("watermark_to", models.DateTimeField(blank=True, null=True)),
                ("permit_count", models.PositiveIntegerField(default=0)),
                ("recipient_count", models.PositiveIntegerField(default=0)),
                ("sent_count", models.PositiveIntegerField(default=0)),
                ("recipients", models.JSONField(blank=True, default=list)),
                ("permit_external_ids", models.JSONField(blank=True, default=list)),
                ("subject", models.CharField(blank=True, max_length=255)),
                ("success", models.BooleanField(db_index=True, default=False)),
                ("error_message", models.TextField(blank=True)),
                ("started_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "sync_run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="alert_runs",
                        to="openskagit.sedrowoolleypermitsyncrun",
                    ),
                ),
            ],
            options={
                "ordering": ["-started_at"],
            },
        ),
        migrations.AddIndex(
            model_name="sedrowoolleypermitalertrun",
            index=models.Index(fields=["job_name", "-started_at"], name="openskagit__job_nam_58f635_idx"),
        ),
        migrations.AddIndex(
            model_name="sedrowoolleypermitalertrun",
            index=models.Index(fields=["success", "-started_at"], name="openskagit__success_bf9ed0_idx"),
        ),
    ]
