# Generated by Django 5.2.7 on 2025-11-24 18:06

import django.contrib.gis.db.models.fields
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openskagit', '0030_adjustmentmodelsegment_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adjustmentrunsummary',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='adjustmentrunsummary',
            name='stats',
            field=models.JSONField(default=list, help_text='List of per-market diagnostic rows.'),
        ),
    ]
