# Generated by Django 5.2.7 on 2025-11-24 18:08

import django.contrib.gis.db.models.fields
import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('openskagit', '0031_alter_adjustmentrunsummary_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessor',
            name='centroid_geog',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='assessor',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=384, null=True),
        ),
    ]
