# Generated by Django 5.2.7 on 2026-02-25 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('openskagit', '0031_sedrowoolleypermitalertrun'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='sedrowoolleypermitalertrun',
            new_name='openskagit__job_nam_2527f3_idx',
            old_name='openskagit__job_nam_58f635_idx',
        ),
        migrations.RenameIndex(
            model_name='sedrowoolleypermitalertrun',
            new_name='openskagit__success_06b9e3_idx',
            old_name='openskagit__success_bf9ed0_idx',
        ),
    ]
