# Generated by Django 5.2.7 on 2025-11-25 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openskagit', '0032_assessor_centroid_geog_assessor_embedding'),
    ]

    operations = [
        migrations.AddField(
            model_name='adjustmentrunsummary',
            name='content',
            field=models.JSONField(default=list, help_text='AI Generated Content from Stats'),
        ),
    ]
