# Generated by Django 5.2.7 on 2026-02-25 21:00

import django.contrib.gis.db.models.fields
import django.contrib.postgres.indexes
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openskagit', '0032_rename_openskagit__job_nam_58f635_idx_openskagit__job_nam_2527f3_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoAppraiserParcelSet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('source_filename', models.CharField(max_length=255)),
                ('upload_file', models.FileField(upload_to='coappraiser/uploads/%Y/%m/%d/')),
                ('parcel_id_column', models.CharField(blank=True, max_length=128)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('ready', 'Ready'), ('partial', 'Partial'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('mode_last_used', models.CharField(blank=True, max_length=20)),
                ('total_rows', models.PositiveIntegerField(default=0)),
                ('parsed_rows', models.PositiveIntegerField(default=0)),
                ('unique_parcel_count', models.PositiveIntegerField(default=0)),
                ('found_count', models.PositiveIntegerField(default=0)),
                ('missing_count', models.PositiveIntegerField(default=0)),
                ('missing_geometry_count', models.PositiveIntegerField(default=0)),
                ('duplicate_count', models.PositiveIntegerField(default=0)),
                ('upload_notes', models.JSONField(blank=True, default=dict)),
                ('created_by_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'coappraiser_parcel_set',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='coappraiser_status_2953d3_idx')],
            },
        ),
        migrations.CreateModel(
            name='CoAppraiserParcelSetItem',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('source_row', models.PositiveIntegerField(default=0)),
                ('parcel_number_raw', models.CharField(blank=True, max_length=128)),
                ('parcel_number_normalized', models.CharField(db_index=True, max_length=64)),
                ('duplicate_instances', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('ready', 'Ready'), ('missing', 'Missing Parcel'), ('missing_geometry', 'Missing Geometry')], db_index=True, default='ready', max_length=32)),
                ('situs_address', models.CharField(blank=True, max_length=300, null=True)),
                ('point_geog', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('point_2926', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=2926)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('x_2926', models.FloatField(blank=True, null=True)),
                ('y_2926', models.FloatField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parcel', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coappraiser_set_items', to='openskagit.masterparcel')),
                ('parcel_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='openskagit.coappraiserparcelset')),
            ],
            options={
                'db_table': 'coappraiser_parcel_set_item',
                'ordering': ['source_row', 'parcel_number_normalized'],
                'indexes': [models.Index(fields=['parcel_set', 'status'], name='coappraiser_parcel__aef221_idx'), models.Index(fields=['parcel_set', 'source_row'], name='coappraiser_parcel__5e68c1_idx'), django.contrib.postgres.indexes.GistIndex(fields=['point_geog'], name='coappraiser_point_g_967d50_gist'), django.contrib.postgres.indexes.GistIndex(fields=['point_2926'], name='coappraiser_point_2_e7f0c8_gist')],
                'constraints': [models.UniqueConstraint(fields=('parcel_set', 'parcel_number_normalized'), name='uniq_coappraiser_parcel_set_item_norm')],
            },
        ),
        migrations.CreateModel(
            name='CoAppraiserRoutePlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mode', models.CharField(choices=[('neighborhood', 'Neighborhood (walkable / dense)'), ('driving', 'Driving (house-to-house)')], db_index=True, max_length=20)),
                ('routing_profile', models.CharField(default='driving', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('target_stops', models.PositiveIntegerField(default=35)),
                ('min_stops', models.PositiveIntegerField(default=30)),
                ('max_stops', models.PositiveIntegerField(default=45)),
                ('grid_cell_size_m', models.PositiveIntegerField(default=1800)),
                ('depot_name', models.CharField(blank=True, max_length=255)),
                ('depot_lat', models.FloatField()),
                ('depot_lon', models.FloatField()),
                ('depot_point_geog', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('cluster_count', models.PositiveIntegerField(default=0)),
                ('routed_stop_count', models.PositiveIntegerField(default=0)),
                ('excluded_stop_count', models.PositiveIntegerField(default=0)),
                ('summary', models.JSONField(blank=True, default=dict)),
                ('result', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parcel_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_plans', to='openskagit.coappraiserparcelset')),
            ],
            options={
                'db_table': 'coappraiser_route_plan',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['parcel_set', '-created_at'], name='coappraiser_parcel__849f4b_idx'), models.Index(fields=['status', '-created_at'], name='coappraiser_status_95932c_idx')],
            },
        ),
    ]
