# Generated by Django 5.2.7 on 2025-11-30 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openskagit', '0034_matchdatabase'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessor',
            name='elev',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
