# Generated by Django 5.2.7 on 2025-12-01 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openskagit', '0035_assessor_elev'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessor',
            name='dist_city_center',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assessor',
            name='dist_fire_station',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assessor',
            name='dist_hospital',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assessor',
            name='dist_minor_road',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assessor',
            name='dist_park',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assessor',
            name='dist_school',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assessor',
            name='dist_supermarket',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assessor',
            name='dist_trailhead',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
