# Generated by Django 5.2.7 on 2025-12-01 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openskagit', '0036_assessor_dist_city_center_assessor_dist_fire_station_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessor',
            name='age',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assessor',
            name='age_bucket',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='assessor',
            name='age_sq',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assessor',
            name='full_bathrooms',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assessor',
            name='half_bathrooms',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assessor',
            name='has_deck',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assessor',
            name='has_finished_basement',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assessor',
            name='has_pool',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assessor',
            name='has_shop',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assessor',
            name='improvement_year_built',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assessor',
            name='neighborhood_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='assessor',
            name='number_of_fireplaces',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assessor',
            name='number_of_outbuildings',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assessor',
            name='number_of_sheds',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assessor',
            name='number_of_shops',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assessor',
            name='renovation_age',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assessor',
            name='total_basement_area',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assessor',
            name='total_deck_area',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assessor',
            name='total_garage_area',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assessor',
            name='total_improvement_value',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assessor',
            name='total_outbuilding_area',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assessor',
            name='total_porch_area',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
