# Generated by Django 5.2.7 on 2025-12-05 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openskagit', '0037_improvements_etl_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessorWaterfacts',
            fields=[
                ('parcel_number', models.TextField(primary_key=True, serialize=False)),
                ('public_water_available', models.BooleanField(blank=True, null=True)),
                ('public_water_system_id', models.TextField(blank=True, null=True)),
                ('in_instream_flow_rule_area', models.BooleanField(blank=True, null=True)),
                ('instream_flow_rule_name', models.TextField(blank=True, null=True)),
                ('has_pou_water_right', models.BooleanField(blank=True, null=True)),
                ('pou_right_numbers', models.JSONField(blank=True, null=True)),
                ('nearest_diversion_right', models.TextField(blank=True, null=True)),
                ('nearest_diversion_distance_m', models.FloatField(blank=True, null=True)),
                ('nearest_right_priority_date', models.DateField(blank=True, null=True)),
                ('low_flow_stream_area', models.BooleanField(blank=True, null=True)),
                ('surface_water_limited', models.BooleanField(blank=True, null=True)),
                ('water_feasibility_rating', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'assessor_waterfacts',
                'managed': False,
            },
        ),
    ]
