# Generated by Django 5.2.7 on 2025-12-05 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('openskagit', '0038_assessorwaterfacts'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assessorwaterfacts',
            options={'managed': True},
        ),
    ]
