# Generated by Django 5.2.7 on 2026-03-25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("openskagit", "0038_property_record_alert_watchlist_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="MountVernonPermitSyncRun",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("run_id", models.CharField(db_index=True, max_length=40, unique=True)),
                ("dry_run", models.BooleanField(default=False)),
                ("max_pages", models.PositiveIntegerField(blank=True, null=True)),
                ("workers", models.PositiveIntegerField(default=1)),
                ("delay_ms", models.PositiveIntegerField(default=250)),
                ("started_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("duration_seconds", models.FloatField(blank=True, null=True)),
                ("list_pages_fetched", models.PositiveIntegerField(default=0)),
                ("detail_pages_fetched", models.PositiveIntegerField(default=0)),
                ("permits_seen", models.PositiveIntegerField(default=0)),
                ("permits_new", models.PositiveIntegerField(default=0)),
                ("permits_updated", models.PositiveIntegerField(default=0)),
                ("permits_unchanged", models.PositiveIntegerField(default=0)),
                ("permit_failures", models.PositiveIntegerField(default=0)),
                ("failures", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-started_at"],
                "indexes": [
                    models.Index(fields=["-started_at"], name="openskagit__started_8daa39_idx"),
                    models.Index(fields=["finished_at"], name="openskagit__finishe_4fe1d7_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="MountVernonPermit",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("external_id", models.CharField(db_index=True, max_length=36, unique=True)),
                ("detail_url", models.URLField(max_length=1000)),
                ("source_list_url", models.URLField(blank=True, max_length=1000)),
                ("source_page_number", models.PositiveIntegerField(default=0)),
                ("case_number", models.CharField(blank=True, db_index=True, max_length=64)),
                ("reference_number", models.CharField(blank=True, db_index=True, max_length=64)),
                ("case_type", models.CharField(blank=True, db_index=True, max_length=255)),
                ("status", models.CharField(blank=True, db_index=True, max_length=120)),
                ("status_text", models.CharField(blank=True, max_length=255)),
                ("status_date", models.DateField(blank=True, db_index=True, null=True)),
                ("site_address_line1", models.CharField(blank=True, max_length=500)),
                ("site_city_state_postal", models.CharField(blank=True, max_length=255)),
                ("primary_contact", models.CharField(blank=True, max_length=255)),
                ("primary_contractor", models.CharField(blank=True, max_length=255)),
                ("parcel_number", models.CharField(blank=True, db_index=True, max_length=120)),
                ("parcel_url", models.URLField(blank=True, max_length=1000)),
                ("created_on", models.DateField(blank=True, db_index=True, null=True)),
                ("submitted_on", models.DateField(blank=True, db_index=True, null=True)),
                ("approved_on", models.DateField(blank=True, db_index=True, null=True)),
                ("issued_on", models.DateField(blank=True, db_index=True, null=True)),
                ("closed_on", models.DateField(blank=True, db_index=True, null=True)),
                ("application_expires_on", models.DateField(blank=True, db_index=True, null=True)),
                ("project_name", models.TextField(blank=True)),
                ("project_description", models.TextField(blank=True)),
                ("latitude", models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ("longitude", models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ("content_hash", models.CharField(db_index=True, max_length=64)),
                ("summary_payload", models.JSONField(blank=True, default=dict)),
                ("detail_payload", models.JSONField(blank=True, default=dict)),
                ("map_points_payload", models.JSONField(blank=True, default=dict)),
                ("summary_html", models.TextField(blank=True)),
                ("detail_html", models.TextField(blank=True)),
                ("last_synced_at", models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-status_date", "-updated_at"],
                "indexes": [
                    models.Index(fields=["case_number", "status"], name="openskagit__case_nu_22c498_idx"),
                    models.Index(fields=["status", "-status_date"], name="openskagit__status_8805f0_idx"),
                    models.Index(fields=["parcel_number", "-status_date"], name="openskagit__parcel__7bc8eb_idx"),
                    models.Index(fields=["-last_synced_at"], name="openskagit__last_sy_77f8b8_idx"),
                ],
            },
        ),
    ]
