# Generated by Django 5.2.7 on 2025-12-05 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openskagit', '0039_alter_assessorwaterfacts_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessor',
            name='calculated_square_footage',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
