# Generated by Django 5.2.7 on 2026-03-25

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("openskagit", "0039_mount_vernon_permit_models"),
    ]

    operations = [
        migrations.CreateModel(
            name="CitizenSurveyParticipant",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("participant_id", models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ("civic_topic_interests", models.JSONField(blank=True, default=list)),
                ("city_interests", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="CitizenSurveyQuestion",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("prompt", models.TextField()),
                (
                    "week_start_date",
                    models.DateField(
                        db_index=True,
                        help_text="Monday date for this weekly survey question (Pacific Time week).",
                        unique=True,
                    ),
                ),
                ("is_published", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-week_start_date"],
                "indexes": [models.Index(fields=["is_published", "week_start_date"], name="citizen_q_pub_week_idx")],
            },
        ),
        migrations.CreateModel(
            name="CitizenSurveyReminder",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="CitizenSurveyOption",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("label", models.CharField(max_length=120)),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "question",
                    models.ForeignKey(on_delete=models.deletion.CASCADE, related_name="options", to="openskagit.citizensurveyquestion"),
                ),
            ],
            options={
                "ordering": ["sort_order", "id"],
                "constraints": [
                    models.UniqueConstraint(fields=("question", "sort_order"), name="citizen_survey_option_order_uniq")
                ],
            },
        ),
        migrations.CreateModel(
            name="CitizenSurveyResponse",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("comment", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "option",
                    models.ForeignKey(on_delete=models.deletion.CASCADE, related_name="responses", to="openskagit.citizensurveyoption"),
                ),
                (
                    "participant",
                    models.ForeignKey(
                        on_delete=models.deletion.CASCADE,
                        related_name="survey_responses",
                        to="openskagit.citizensurveyparticipant",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(on_delete=models.deletion.CASCADE, related_name="responses", to="openskagit.citizensurveyquestion"),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [models.Index(fields=["question", "option"], name="citizen_resp_q_opt_idx")],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("question", "participant"),
                        name="citizen_survey_one_response_per_question",
                    )
                ],
            },
        ),
    ]
