# Generated by Django 5.2.7 on 2026-03-26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("openskagit", "0040_citizen_weekly_survey_models"),
    ]

    operations = [
        migrations.CreateModel(
            name="CitizenSurveyReminderSend",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("sent_at", models.DateTimeField(auto_now_add=True)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=models.deletion.CASCADE,
                        related_name="reminder_sends",
                        to="openskagit.citizensurveyquestion",
                    ),
                ),
                (
                    "reminder",
                    models.ForeignKey(
                        on_delete=models.deletion.CASCADE,
                        related_name="sends",
                        to="openskagit.citizensurveyreminder",
                    ),
                ),
            ],
            options={
                "ordering": ["-sent_at"],
                "indexes": [
                    models.Index(fields=["question", "sent_at"], name="citizen_rem_q_sent_idx"),
                    models.Index(fields=["reminder", "sent_at"], name="citizen_rem_r_sent_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("question", "reminder"),
                        name="citizen_survey_reminder_send_uniq",
                    )
                ],
            },
        ),
    ]
