# Generated by Django 5.2.7 on 2025-12-05 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openskagit', '0040_assessor_calculated_square_footage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessorwaterfacts',
            name='aquifer_yield_category',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assessorwaterfacts',
            name='nearest_well_depth',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assessorwaterfacts',
            name='nearest_well_distance_m',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assessorwaterfacts',
            name='nearest_well_id',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assessorwaterfacts',
            name='nearest_well_yield',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assessorwaterfacts',
            name='well_drilling_feasible',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
