# Generated by Django 5.2.7 on 2026-03-26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("openskagit", "0041_citizensurveyremindersend"),
    ]

    operations = [
        migrations.AddField(
            model_name="citizensurveyquestion",
            name="metadata",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="citizensurveyquestion",
            name="week_start_date",
            field=models.DateField(
                db_index=True,
                help_text="Sunday date for this weekly survey question (Pacific Time week).",
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="citizensurveyresponse",
            name="focused_city",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="citizensurveyresponse",
            name="is_staff_debug",
            field=models.BooleanField(default=False),
        ),
        migrations.RemoveConstraint(
            model_name="citizensurveyresponse",
            name="citizen_survey_one_response_per_question",
        ),
        migrations.AddConstraint(
            model_name="citizensurveyresponse",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_staff_debug", False)),
                fields=("question", "participant"),
                name="citizen_survey_one_response_per_question",
            ),
        ),
        migrations.AddIndex(
            model_name="citizensurveyresponse",
            index=models.Index(fields=["question", "focused_city"], name="citizen_resp_q_city_idx"),
        ),
    ]
