# Generated by Django 5.2.7 on 2025-12-06 13:53

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openskagit', '0041_assessorwaterfacts_aquifer_yield_category_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='improvements',
            index=models.Index(fields=['roll'], name='improvement_roll_id_0d3ef8_idx'),
        ),
        migrations.AddIndex(
            model_name='improvements',
            index=models.Index(fields=['parcel_number'], name='improvement_parcel__57e9d4_idx'),
        ),
        migrations.AddIndex(
            model_name='improvements',
            index=models.Index(fields=['improvement_detail_type_code'], name='improvement_improve_ad487d_idx'),
        ),
        migrations.AddIndex(
            model_name='improvements',
            index=models.Index(fields=['condition_code'], name='improvement_conditi_3ee3cc_idx'),
        ),
        migrations.AddIndex(
            model_name='improvements',
            index=models.Index(fields=['improvement_detail_value'], name='improvement_improve_50b038_idx'),
        ),
        migrations.AddIndex(
            model_name='improvements',
            index=models.Index(fields=['effective_year_built'], name='improvement_effecti_0e3ddc_idx'),
        ),
    ]
