# Generated by Django 5.2.7 on 2025-12-08 20:32

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openskagit', '0042_assessorwaterfacts_in_wellhead_protection_area_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterParcel',
            fields=[
                ('parcel_number', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('aid', models.IntegerField(blank=True, null=True)),
                ('building_value', models.FloatField(blank=True, null=True)),
                ('impr_land_value', models.FloatField(blank=True, null=True)),
                ('unimpr_land_value', models.FloatField(blank=True, null=True)),
                ('timber_land_value', models.FloatField(blank=True, null=True)),
                ('assessed_value', models.FloatField(blank=True, null=True)),
                ('taxable_value', models.FloatField(blank=True, null=True)),
                ('total_market_value', models.FloatField(blank=True, null=True)),
                ('acres', models.FloatField(blank=True, null=True)),
                ('sale_price', models.FloatField(blank=True, null=True)),
                ('price_per_sqft', models.FloatField(blank=True, null=True)),
                ('year_built', models.IntegerField(blank=True, null=True)),
                ('living_area', models.IntegerField(blank=True, null=True)),
                ('buildingstyle', models.CharField(blank=True, max_length=100, null=True)),
                ('plumbing', models.CharField(blank=True, max_length=100, null=True)),
                ('garagesqft', models.IntegerField(blank=True, null=True)),
                ('heat_air_cond', models.CharField(blank=True, max_length=100, null=True)),
                ('fireplace', models.CharField(blank=True, max_length=100, null=True)),
                ('finishedbasement', models.IntegerField(blank=True, null=True)),
                ('number_of_bedrooms', models.IntegerField(blank=True, null=True)),
                ('eff_year_built', models.IntegerField(blank=True, null=True)),
                ('unfinishedbasement', models.IntegerField(blank=True, null=True)),
                ('fire_district', models.CharField(blank=True, max_length=50, null=True)),
                ('school_district', models.CharField(blank=True, max_length=50, null=True)),
                ('city_district', models.CharField(blank=True, max_length=50, null=True)),
                ('levy_code', models.CharField(blank=True, max_length=20, null=True)),
                ('proptype', models.CharField(blank=True, max_length=10, null=True)),
                ('hasseptic', models.BooleanField(default=False)),
                ('land_use_code', models.CharField(blank=True, max_length=10, null=True)),
                ('land_use_description', models.CharField(blank=True, max_length=200, null=True)),
                ('hood_code', models.CharField(blank=True, max_length=20, null=True)),
                ('hood_description', models.CharField(blank=True, max_length=200, null=True)),
                ('has_unit', models.BooleanField(default=False)),
                ('situs_address', models.CharField(blank=True, max_length=300, null=True)),
                ('total_baths', models.FloatField(blank=True, null=True)),
                ('year_built_max', models.IntegerField(blank=True, null=True)),
                ('year_built_min', models.IntegerField(blank=True, null=True)),
                ('total_living_area', models.FloatField(blank=True, null=True)),
                ('total_garage_area', models.FloatField(blank=True, null=True)),
                ('total_deck_area', models.FloatField(blank=True, null=True)),
                ('total_porch_area', models.FloatField(blank=True, null=True)),
                ('total_basement_area', models.FloatField(blank=True, null=True)),
                ('total_shop_area', models.FloatField(blank=True, null=True)),
                ('total_shed_count', models.IntegerField(blank=True, null=True)),
                ('has_pool', models.BooleanField(default=False)),
                ('quality_score', models.FloatField(blank=True, null=True)),
                ('condition_score', models.FloatField(blank=True, null=True)),
                ('building_style', models.CharField(blank=True, max_length=50, null=True)),
                ('effective_yr_blt', models.IntegerField(blank=True, null=True)),
                ('main_structure_count', models.IntegerField(blank=True, null=True)),
                ('flag_multi_structure', models.BooleanField(default=False)),
                ('final_living_area', models.FloatField(blank=True, null=True)),
                ('final_year_built', models.IntegerField(blank=True, null=True)),
                ('final_garage_area', models.FloatField(blank=True, null=True)),
                ('final_eff_yr_blt', models.IntegerField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'master_parcel',
                'indexes': [models.Index(fields=['parcel_number'], name='master_parc_parcel__04e153_idx'), models.Index(fields=['hood_code'], name='master_parc_hood_co_cdede5_idx'), models.Index(fields=['land_use_code'], name='master_parc_land_us_cc8eeb_idx')],
            },
        ),
    ]
