# Generated by Django 5.2.7 on 2026-04-23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("openskagit", "0042_citizensurvey_city_and_metadata"),
    ]

    operations = [
        migrations.AddField(
            model_name="masterparcel",
            name="tax_status",
            field=models.CharField(blank=True, db_index=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name="masterparcel",
            name="tax_status_updated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
