# Generated by Django 5.2.7 on 2025-12-09 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("openskagit", "0043_assessorwaterfacts_in_wellhead_protection_area_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="masterparcel",
            name="total_shop_count",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="masterparcel",
            name="total_shed_area",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
