# Generated by Django 5.2.7 on 2025-12-08 21:21

import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields
import django.contrib.postgres.indexes
import django.db.models.deletion
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openskagit', '0044_masterparcel_shop_shed_rollups'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParcelGeometry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=3857)),
                ('embedding', pgvector.django.vector.VectorField(blank=True, dimensions=384, null=True)),
                ('centroid_geog', django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326)),
                ('elev', models.FloatField(blank=True, null=True)),
                ('elevation', models.FloatField(blank=True, null=True)),
                ('slope', models.FloatField(blank=True, null=True)),
                ('aspect', models.FloatField(blank=True, null=True)),
                ('aspect_dir', models.TextField(blank=True, null=True)),
                ('in_flood_zone', models.BooleanField(blank=True, null=True)),
                ('flood_distance', models.FloatField(blank=True, null=True)),
                ('flood_static_bfe', models.FloatField(blank=True, null=True)),
                ('flood_depth', models.FloatField(blank=True, null=True)),
                ('flood_velocity', models.FloatField(blank=True, null=True)),
                ('flood_sfha', models.TextField(blank=True, null=True)),
                ('flood_zone', models.TextField(blank=True, null=True)),
                ('flood_zone_subtype', models.TextField(blank=True, null=True)),
                ('flood_zone_id', models.TextField(blank=True, null=True)),
                ('dist_major_road', models.FloatField(blank=True, null=True)),
                ('dist_floodway', models.FloatField(blank=True, null=True)),
                ('dist_minor_road', models.FloatField(blank=True, null=True)),
                ('dist_city_center', models.FloatField(blank=True, null=True)),
                ('dist_school', models.FloatField(blank=True, null=True)),
                ('dist_park', models.FloatField(blank=True, null=True)),
                ('dist_supermarket', models.FloatField(blank=True, null=True)),
                ('dist_hospital', models.FloatField(blank=True, null=True)),
                ('dist_fire_station', models.FloatField(blank=True, null=True)),
                ('dist_trailhead', models.FloatField(blank=True, null=True)),
                ('geom_backup', django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=3857)),
                ('geom_2926', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=2926)),
                ('parcel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='geometry', to='openskagit.masterparcel')),
            ],
            options={
                'indexes': [django.contrib.postgres.indexes.GistIndex(fields=['geom'], name='openskagit__geom_05e325_gist'), django.contrib.postgres.indexes.GistIndex(fields=['geom_2926'], name='openskagit__geom_29_277639_gist'), django.contrib.postgres.indexes.GistIndex(fields=['centroid_geog'], name='openskagit__centroi_0c7376_gist')],
            },
        ),
    ]
