# Generated by Django 5.2.7 on 2025-12-08 22:29

import django.contrib.postgres.fields
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openskagit', '0045_assessorwaterfacts_in_wellhead_protection_area_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferenceDataImportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataset_name', models.CharField(max_length=100)),
                ('source_path', models.CharField(max_length=500)),
                ('table_name', models.CharField(max_length=100)),
                ('success', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('row_count', models.IntegerField(default=0)),
                ('srid', models.IntegerField(default=2926)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
