# Generated by Django 5.2.7 on 2025-12-08 23:28

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openskagit', '0046_referencedataimportlog_and_more'),
    ]

    operations = [
      
    ]
