# Generated by Django 5.2.7 on 2025-12-09 18:56

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openskagit', '0047_assessorwaterfacts_in_wellhead_protection_area_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParcelPlanningFacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone_code', models.CharField(blank=True, max_length=50, null=True)),
                ('zoning_jurisdiction', models.CharField(blank=True, max_length=50, null=True)),
                ('zoning_min_lot_size_sqft', models.FloatField(blank=True, null=True)),
                ('zoning_max_lot_coverage_pct', models.FloatField(blank=True, null=True)),
                ('zoning_max_height_ft', models.FloatField(blank=True, null=True)),
                ('zoning_front_setback_ft', models.FloatField(blank=True, null=True)),
                ('zoning_side_setback_ft', models.FloatField(blank=True, null=True)),
                ('zoning_rear_setback_ft', models.FloatField(blank=True, null=True)),
                ('zoning_allows_adu', models.BooleanField(blank=True, null=True)),
                ('zoning_allows_duplex', models.BooleanField(blank=True, null=True)),
                ('zoning_allows_multifamily', models.BooleanField(blank=True, null=True)),
                ('in_wetland', models.BooleanField(blank=True, null=True)),
                ('pct_area_in_wetland', models.FloatField(blank=True, null=True)),
                ('in_stream_buffer', models.BooleanField(blank=True, null=True)),
                ('pct_area_in_stream_buffer', models.FloatField(blank=True, null=True)),
                ('dist_to_nearest_stream_ft', models.FloatField(blank=True, null=True)),
                ('stream_type', models.CharField(blank=True, max_length=20, null=True)),
                ('stream_buffer_required_ft', models.FloatField(blank=True, null=True)),
                ('in_sfha', models.BooleanField(blank=True, null=True)),
                ('pct_area_in_sfha', models.FloatField(blank=True, null=True)),
                ('in_floodway', models.BooleanField(blank=True, null=True)),
                ('pct_area_in_floodway', models.FloatField(blank=True, null=True)),
                ('in_shoreline_jurisdiction', models.BooleanField(blank=True, null=True)),
                ('shoreline_env_designation', models.CharField(blank=True, max_length=50, null=True)),
                ('dist_to_shoreline_ft', models.FloatField(blank=True, null=True)),
                ('in_geologic_hazard_area', models.BooleanField(blank=True, null=True)),
                ('max_slope_pct', models.FloatField(blank=True, null=True)),
                ('pct_area_slope_gt_30', models.FloatField(blank=True, null=True)),
                ('buildable_area_sqft', models.FloatField(blank=True, null=True)),
                ('public_water_available', models.BooleanField(blank=True, null=True)),
                ('public_water_system_id', models.CharField(blank=True, max_length=100, null=True)),
                ('dist_to_water_main_ft', models.FloatField(blank=True, null=True)),
                ('public_sewer_available', models.BooleanField(blank=True, null=True)),
                ('sewer_district_id', models.CharField(blank=True, max_length=100, null=True)),
                ('dist_to_sewer_main_ft', models.FloatField(blank=True, null=True)),
                ('in_instream_flow_rule_area', models.BooleanField(blank=True, null=True)),
                ('instream_flow_rule_name', models.CharField(blank=True, max_length=200, null=True)),
                ('nearest_well_distance_ft', models.FloatField(blank=True, null=True)),
                ('well_density_per_acre', models.FloatField(blank=True, null=True)),
                ('in_wellhead_protection_zone', models.BooleanField(blank=True, null=True)),
                ('wellhead_zone_category', models.CharField(blank=True, max_length=20, null=True)),
                ('primary_access_type', models.CharField(blank=True, max_length=50, null=True)),
                ('dist_to_public_road_ft', models.FloatField(blank=True, null=True)),
                ('dist_to_driveable_access_ft', models.FloatField(blank=True, null=True)),
                ('fire_district_id', models.CharField(blank=True, max_length=50, null=True)),
                ('school_district_id', models.CharField(blank=True, max_length=50, null=True)),
                ('city_jurisdiction', models.CharField(blank=True, max_length=50, null=True)),
                ('legislative_district_id', models.CharField(blank=True, max_length=50, null=True)),
                ('voting_district_id', models.CharField(blank=True, max_length=50, null=True)),
                ('in_npdes_area', models.BooleanField(blank=True, null=True)),
                ('in_historic_register', models.BooleanField(blank=True, null=True)),
                ('in_historic_district', models.BooleanField(blank=True, null=True)),
                ('in_airport_environs', models.BooleanField(blank=True, null=True)),
                ('airport_environs_zone', models.CharField(blank=True, max_length=20, null=True)),
                ('has_recent_permits_5yr', models.BooleanField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('parcel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='planning_facts', to='openskagit.masterparcel')),
            ],
            options={
                'db_table': 'parcel_planning_facts',
                'indexes': [models.Index(fields=['zone_code'], name='parcel_plan_zone_co_94ed8b_idx'), models.Index(fields=['public_water_available'], name='parcel_plan_public__1b66b9_idx'), models.Index(fields=['public_sewer_available'], name='parcel_plan_public__324ec8_idx'), models.Index(fields=['in_sfha'], name='parcel_plan_in_sfha_795780_idx'), models.Index(fields=['in_floodway'], name='parcel_plan_in_floo_def35d_idx'), models.Index(fields=['in_shoreline_jurisdiction'], name='parcel_plan_in_shor_184cb2_idx')],
            },
        ),
    ]
