# Generated by Django 5.2.7 on 2025-12-09 19:01

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openskagit', '0048_assessorwaterfacts_in_wellhead_protection_area_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessorwaterfacts',
            name='in_wellhead_protection_area',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='assessorwaterfacts',
            name='pou_right_numbers',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True, null=True), blank=True, null=True, size=None),
        ),
    ]
