# Generated by Django 5.2.7 on 2025-12-09 19:06

import django.contrib.gis.db.models.fields
import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openskagit', '0049_assessorwaterfacts_in_wellhead_protection_area_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LidarTile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('geom', django.contrib.gis.db.models.fields.PolygonField(srid=2926)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_processed', models.DateTimeField(blank=True, null=True)),
                ('parcels', models.ManyToManyField(blank=True, related_name='lidar_tiles', to='openskagit.masterparcel')),
            ],
            options={
                'indexes': [django.contrib.postgres.indexes.GistIndex(fields=['geom'], name='openskagit__geom_d2e88a_gist')],
            },
        ),
    ]
