# Generated by Django 5.2.7 on 2025-12-09 21:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openskagit', '0050_lidartile'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParcelLidarStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_elevation_ft', models.FloatField(help_text='Lowest ground point, NAVD88 feet')),
                ('max_elevation_ft', models.FloatField(help_text='Highest point detected (e.g., roof or tree top)')),
                ('mean_terrain_z_ft', models.FloatField(help_text='Average bare earth elevation (Ground Class 2)')),
                ('terrain_roughness', models.FloatField(help_text='Standard deviation of Z')),
                ('est_canopy_height_ft', models.FloatField(help_text='Max Z - Mean ground Z')),
                ('canopy_cover_percent', models.FloatField(blank=True, null=True)),
                ('structure_footprint_sqft', models.FloatField(blank=True, null=True)),
                ('max_structure_height_ft', models.FloatField(blank=True, null=True)),
                ('mean_intensity', models.FloatField(blank=True, null=True)),
                ('slope_hazard_area_sqft', models.FloatField(blank=True, null=True)),
                ('point_density_sqft', models.FloatField(help_text='LiDAR points per sq ft')),
                ('last_calculated', models.DateTimeField(auto_now=True)),
                ('parcel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lidar_stats', to='openskagit.parcel')),
            ],
            options={
                'verbose_name_plural': 'Parcel Lidar Stats',
            },
        ),
    ]
