# Generated by Django 5.2.7 on 2025-12-10 00:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openskagit', '0052_rename_assessorwaterfacts_parcelwaterfacts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcelplanningfacts',
            name='parcel',
            field=models.OneToOneField(db_column='parcel_id', on_delete=django.db.models.deletion.CASCADE, to='openskagit.masterparcel'),
        ),
    ]
