# Generated by Django 5.2.7 on 2025-12-11 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openskagit', '0053_alter_parcelplanningfacts_parcel'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcelplanningfacts',
            name='in_big_lake_mitigation_area',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parcelplanningfacts',
            name='pct_area_in_shoreline',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
