# Generated by Django 5.2.7 on 2025-12-11 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openskagit', '0054_parcelplanningfacts_in_big_lake_mitigation_area_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcelplanningfacts',
            name='dist_to_wetland_ft',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parcelplanningfacts',
            name='in_wetland_buffer',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parcelplanningfacts',
            name='wetland_buffer_intersect_area',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parcelplanningfacts',
            name='wetland_intersect_area',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
