# Generated by Django 5.2.7 on 2025-12-11 20:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openskagit', '0055_parcelplanningfacts_dist_to_wetland_ft_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZoningRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone_code', models.CharField(max_length=50)),
                ('jurisdiction', models.CharField(max_length=100)),
                ('min_lot_size_sqft', models.FloatField(blank=True, null=True)),
                ('max_lot_coverage_pct', models.FloatField(blank=True, null=True)),
                ('max_height_ft', models.FloatField(blank=True, null=True)),
                ('front_setback_ft', models.FloatField(blank=True, null=True)),
                ('side_setback_ft', models.FloatField(blank=True, null=True)),
                ('rear_setback_ft', models.FloatField(blank=True, null=True)),
                ('allows_adu', models.BooleanField(blank=True, null=True)),
                ('allows_duplex', models.BooleanField(blank=True, null=True)),
                ('allows_multifamily', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'zoning_rules',
                'indexes': [models.Index(fields=['zone_code'], name='zoning_rule_zone_co_570f5f_idx'), models.Index(fields=['jurisdiction'], name='zoning_rule_jurisdi_e59f5d_idx')],
                'unique_together': {('zone_code', 'jurisdiction')},
            },
        ),
        migrations.AddField(
            model_name='parcelplanningfacts',
            name='zoning_rule',
            field=models.ForeignKey(blank=True, db_column='zoning_rule_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='openskagit.zoningrule'),
        ),
    ]
