# Generated by Django 5.2.7 on 2025-12-11 20:59

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('openskagit', '0056_zoningrule_parcelplanningfacts_zoning_rule'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                ALTER TABLE openskagit_parcelgeometry
                ALTER COLUMN centroid_geog
                TYPE geometry(Point,4326)
                USING centroid_geog::geometry(Point,4326);
            """,
            reverse_sql="""
                ALTER TABLE openskagit_parcelgeometry
                ALTER COLUMN centroid_geog
                TYPE geography(Point,4326)
                USING centroid_geog::geography;
            """
        )
    ]
