# Generated by Django 5.2.7 on 2025-12-11 22:11

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('openskagit', '0057_alter_parcelgeometry_centroid_geog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcelgeometry',
            name='centroid_geog',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
