# Generated by Django 5.2.7 on 2025-12-12 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openskagit', '0058_alter_parcelgeometry_centroid_geog'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcelplanningfacts',
            name='in_skagit_mitigation_area',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parcelplanningfacts',
            name='skagit_mitigation_class',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
