# Generated by Django 5.2.7 on 2025-12-12 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openskagit', '0059_parcelplanningfacts_in_skagit_mitigation_area_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterparcel',
            name='census_block_group_geoid',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
