# Generated by Django 5.2.7 on 2025-12-12 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openskagit', '0060_masterparcel_census_block_group_geoid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='masterparcel',
            name='census_block_group_geoid',
        ),
        migrations.AddField(
            model_name='parcelplanningfacts',
            name='census_block_group_geoid',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
