# Generated by Django 5.2.7 on 2025-12-15 15:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openskagit', '0061_remove_masterparcel_census_block_group_geoid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExperimentRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Descriptive name for this experiment', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('mode', models.CharField(default='sfr', max_length=50)),
                ('market_group_col', models.CharField(default='valuation_area', max_length=100)),
                ('countywide', models.BooleanField(default=False)),
                ('predictor_profile', models.CharField(default='baseline', max_length=100)),
                ('interaction_bundle', models.CharField(default='standard', max_length=100)),
                ('full_config', models.JSONField(default=dict, help_text='Complete experiment parameters')),
                ('total_observations', models.IntegerField(blank=True, null=True)),
                ('segment_count', models.IntegerField(blank=True, null=True)),
                ('global_cod', models.FloatField(blank=True, null=True)),
                ('global_prd', models.FloatField(blank=True, null=True)),
                ('global_prb', models.FloatField(blank=True, null=True)),
                ('global_r2', models.FloatField(blank=True, null=True)),
                ('global_rmse', models.FloatField(blank=True, null=True)),
                ('diagnostics_path', models.CharField(blank=True, max_length=500)),
                ('run_id', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('starred', models.BooleanField(default=False)),
                ('tags', models.JSONField(default=list, help_text='User-defined tags')),
                ('baseline_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='experiments', to='openskagit.experimentrun')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='openskagit__status_10a108_idx'), models.Index(fields=['starred', '-created_at'], name='openskagit__starred_d942b3_idx')],
            },
        ),
    ]
