# Generated by Django 5.2.7 on 2025-12-15 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('openskagit', '0062_remove_parcelgeometry_elevation_experimentrun'),
    ]

    operations = [
       
    ]
