# Generated by Django 5.2.7 on 2025-12-15 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openskagit', '0063_remove_parcelgeometry_elevation'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcelplanningfacts',
            name='anacortes_zone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='parcelplanningfacts',
            name='in_anacortes_zoning',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
