# Generated by Django 5.2.7 on 2025-12-15 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openskagit', '0064_parcelplanningfacts_anacortes_zone_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parcelplanningfacts',
            name='anacortes_zone',
        ),
        migrations.RemoveField(
            model_name='parcelplanningfacts',
            name='in_anacortes_zoning',
        ),
        migrations.RemoveField(
            model_name='parcelplanningfacts',
            name='zoning_allows_adu',
        ),
        migrations.RemoveField(
            model_name='parcelplanningfacts',
            name='zoning_rule',
        ),
        migrations.AddField(
            model_name='parcelplanningfacts',
            name='zoning_adu_owner_occupancy_required',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parcelplanningfacts',
            name='zoning_adus_allowed_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parcelplanningfacts',
            name='zoning_allows_agriculture',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parcelplanningfacts',
            name='zoning_allows_data_center',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parcelplanningfacts',
            name='zoning_allows_forestry',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parcelplanningfacts',
            name='zoning_allows_green_energy',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parcelplanningfacts',
            name='zoning_allows_heavy_industrial',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parcelplanningfacts',
            name='zoning_allows_industrial',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parcelplanningfacts',
            name='zoning_allows_office',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parcelplanningfacts',
            name='zoning_allows_residential',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parcelplanningfacts',
            name='zoning_allows_retail',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parcelplanningfacts',
            name='zoning_allows_warehouse',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parcelplanningfacts',
            name='zoning_general_class',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='parcelplanningfacts',
            name='zoning_last_verified',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parcelplanningfacts',
            name='zoning_max_density_du_ac',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parcelplanningfacts',
            name='zoning_max_far',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parcelplanningfacts',
            name='zoning_max_stories',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parcelplanningfacts',
            name='zoning_max_units_per_lot',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parcelplanningfacts',
            name='zoning_min_density_du_ac',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parcelplanningfacts',
            name='zoning_min_far',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parcelplanningfacts',
            name='zoning_parking_min_apartment',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parcelplanningfacts',
            name='zoning_parking_min_middle_housing',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parcelplanningfacts',
            name='zoning_parking_min_office',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parcelplanningfacts',
            name='zoning_parking_min_residential',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parcelplanningfacts',
            name='zoning_parking_min_restaurant',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parcelplanningfacts',
            name='zoning_parking_min_retail',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parcelplanningfacts',
            name='zoning_reference_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='parcelplanningfacts',
            name='zoning_source',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='parcelplanningfacts',
            name='zoning_specific_class',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
