import csv
from django.core.management.base import BaseCommand
from django.utils.timezone import now

from openskagit.models import AdjustmentCoefficient


class Command(BaseCommand):
    help = "Import adjustment coefficients from a CSV file generated by the regression engine."

    def add_arguments(self, parser):
        parser.add_argument(
            "csv_path",
            type=str,
            help="Path to adj_coeffs_<RUN_ID>.csv"
        )
        parser.add_argument(
            "--run-id",
            type=str,
            default=None,
            help="Optional run ID (otherwise inferred from filename)."
        )

    def handle(self, *args, **options):
        csv_path = options["csv_path"]
        run_id = options["run_id"]

        if not run_id:
            # Try to extract run ID from filename: adj_coeffs_134455.csv → 134455
            import re, os
            base = os.path.basename(csv_path)
            m = re.search(r"adj_coeffs_(\d+)", base)
            run_id = m.group(1) if m else now().strftime("%H%M%S")

        self.stdout.write(self.style.SUCCESS(f"Using run_id = {run_id}"))
        created = 0
        updated = 0

        with open(csv_path, "r") as f:
            reader = csv.DictReader(f)

            for row in reader:
                obj, is_created = AdjustmentCoefficient.objects.update_or_create(
                    market_group=row["market_group"],
                    term=row["term"],
                    run_id=run_id,
                    defaults={
                        "beta": float(row["beta"]),
                        "beta_se": float(row["beta_se"]) if row["beta_se"] else None,
                    },
                )
                if is_created:
                    created += 1
                else:
                    updated += 1

        self.stdout.write(self.style.SUCCESS(
            f"Import complete: {created} created, {updated} updated."
        ))
