import csv
import re
from collections import Counter
from datetime import datetime
from pathlib import Path

from django.conf import settings
from django.core.management.base import BaseCommand, CommandError
from django.db import transaction
from django.db.models import Count
from django.utils.text import slugify

from openskagit.models import (
    MasterParcel,
    ParcelHistory,
    TaxationWithoutRepresentation,
    VoterElection,
    VoterParcelMatch,
    VoterReturnLocation,
    VoterTurnoutRaw,
)


class Command(BaseCommand):
    help = (
        "Ingest the normalized Skagit voter turnout CSV, refresh turnout tables, "
        "match ballots to parcels, and generate the Taxation Without Representation report."
    )

    DEFAULT_SOURCE = (
        settings.BASE_DIR / "data" / "votingresults" / "skagit_turnout_2024_2025.normalized.csv"
    )

    def add_arguments(self, parser):
        parser.add_argument(
            "--csv",
            dest="csv_path",
            default=str(self.DEFAULT_SOURCE),
            help="Path to the normalized turnout CSV generated by prepare_voter_turnout.",
        )
        parser.add_argument(
            "--batch-size",
            type=int,
            default=2000,
            help="Number of rows to bulk insert at a time.",
        )
        parser.add_argument(
            "--tax-threshold",
            type=int,
            default=5000,
            help="Minimum annual tax (dollars) before considering a parcel for the taxation report.",
        )
        parser.add_argument(
            "--election-date",
            help="YYYY-MM-DD election date to target for the taxation report (defaults to latest General).",
        )
        parser.add_argument(
            "--election-slug",
            help="Optional slug to pick a specific election for the taxation report.",
        )
        parser.add_argument(
            "--election-category",
            default="General",
            help="Fallback election category when selecting the default report election.",
        )
        parser.add_argument("--skip-match", action="store_true", help="Skip parcel matching step.")
        parser.add_argument("--skip-report", action="store_true", help="Skip taxation report generation.")
        parser.add_argument(
            "--dry-run",
            action="store_true",
            help="Parse the CSV and log counts without touching the database.",
        )

    def handle(self, *args, **options):
        csv_path = Path(options["csv_path"]).expanduser().resolve()
        if not csv_path.exists():
            raise CommandError(f"CSV file {csv_path} does not exist")

        dry_run = options["dry_run"]
        batch_size = options["batch_size"]

        if dry_run:
            total_rows, elections = self.inspect_csv(csv_path)
            self.stdout.write(
                self.style.WARNING(
                    f"Dry run only – detected {total_rows} rows across {len(elections)} elections"
                )
            )
            for name, count in sorted(elections.items(), key=lambda kv: kv[0]):
                self.stdout.write(f"  {name}: {count} rows")
            return

        self.stdout.write(self.style.MIGRATE_HEADING("Loading voter turnout data"))
        per_election_counts = self.ingest_turnout(csv_path, batch_size)
        for election, count in per_election_counts.items():
            self.stdout.write(f"  {election}: {count} ballots")

        if not options["skip_match"]:
            self.stdout.write(self.style.MIGRATE_HEADING("Attempting parcel matches"))
            created, skipped = self.match_parcels()
            self.stdout.write(
                f"  Created {created} matches; {skipped} ballots still have no parcel match"
            )

        if options["skip_report"]:
            return

        target_election = self.resolve_report_election(options)
        if not target_election:
            self.stdout.write(
                self.style.WARNING(
                    "Could not find an election for the taxation report – skipping this step"
                )
            )
            return

        self.stdout.write(
            self.style.MIGRATE_HEADING(
                f"Building taxation-without-representation report for {target_election.name}"
            )
        )
        flagged = self.build_taxation_report(target_election, options["tax_threshold"])
        self.stdout.write(
            self.style.SUCCESS(
                f"Taxation Without Representation report refreshed with {flagged} flagged parcels"
            )
        )

    # ------------------------------------------------------------------
    # CSV INGESTION
    # ------------------------------------------------------------------

    def inspect_csv(self, path: Path):
        counts = Counter()
        with path.open(newline="", encoding="utf-8") as fh:
            reader = csv.DictReader(fh)
            for row in reader:
                name = row.get("election_name") or "Unknown"
                counts[name] += 1
        return sum(counts.values()), counts

    def ingest_turnout(self, path: Path, batch_size: int):
        election_cache = {}
        cleared_elections = set()
        location_cache = {}
        per_election_counts = Counter()
        buffer = []

        with transaction.atomic():
            with path.open(newline="", encoding="utf-8") as fh:
                reader = csv.DictReader(fh)
                for row in reader:
                    election = self.get_or_create_election(row, election_cache)
                    if election.id not in cleared_elections:
                        VoterTurnoutRaw.objects.filter(election=election).delete()
                        cleared_elections.add(election.id)
                    return_location = self.get_or_create_return_location(row, location_cache)
                    record = self.build_turnout_record(row, election, return_location)
                    buffer.append(record)
                    per_election_counts[election.name] += 1
                    if len(buffer) >= batch_size:
                        VoterTurnoutRaw.objects.bulk_create(buffer, batch_size=batch_size)
                        buffer = []

            if buffer:
                VoterTurnoutRaw.objects.bulk_create(buffer, batch_size=batch_size)

        return per_election_counts

    def get_or_create_election(self, row, cache):
        name = (row.get("election_name") or "").strip() or "Unknown Election"
        category = (row.get("election_category") or "").strip()
        date_str = row.get("election_date")
        if not date_str:
            raise CommandError(f"Missing election_date for row {row}")
        try:
            election_date = datetime.strptime(date_str, "%Y-%m-%d").date()
        except ValueError as exc:
            raise CommandError(f"Invalid election_date '{date_str}': {exc}") from exc

        cache_key = (name, election_date)
        if cache_key in cache:
            return cache[cache_key]

        slug_base = slugify(f"{name}-{election_date}") or slugify(f"{category}-{election_date}")
        slug_base = slug_base or f"election-{election_date}"
        slug = slug_base
        suffix = 1
        while VoterElection.objects.filter(slug=slug).exclude(election_date=election_date).exists():
            slug = f"{slug_base}-{suffix}"
            suffix += 1

        election, _ = VoterElection.objects.get_or_create(
            name=name,
            election_date=election_date,
            defaults={"category": category, "slug": slug},
        )
        cache[cache_key] = election
        return election

    def get_or_create_return_location(self, row, cache):
        name = (row.get("return_location") or row.get("return_location_name") or "").strip()
        method = (row.get("return_method") or "").strip()
        if not name and not method:
            return None
        normalized_name = self.normalize_simple(name)
        normalized_method = self.normalize_simple(method)
        cache_key = (normalized_name, normalized_method)
        if cache_key in cache:
            return cache[cache_key]
        location, _ = VoterReturnLocation.objects.get_or_create(
            normalized_name=normalized_name,
            normalized_method=normalized_method,
            defaults={"name": name or method, "method": method,},
        )
        cache[cache_key] = location
        return location

    def build_turnout_record(self, row, election, return_location):
        sent = self.parse_datetime(row.get("sent_date"))
        received = self.parse_datetime(row.get("received_date"))
        normalized_address = self.normalize_address(
            row.get("normalized_address") or row.get("address")
        )
        normalized_precinct = self.normalize_simple(row.get("normalized_precinct"))
        is_po_box = str(row.get("is_po_box") or "").strip().lower() == "true"

        return VoterTurnoutRaw(
            election=election,
            return_location=return_location,
            ballot_id=(row.get("ballot_id") or "").strip(),
            voter_id=(row.get("voter_id") or "").strip(),
            county=(row.get("county") or "").strip(),
            first_name=(row.get("first_name") or "").strip(),
            last_name=(row.get("last_name") or "").strip(),
            gender=(row.get("gender") or "").strip(),
            ballot_status=(row.get("ballot_status") or "").strip(),
            challenge_reason=(row.get("challenge_reason") or "").strip(),
            sent_date=sent,
            received_date=received,
            address=(row.get("address") or "").strip(),
            normalized_address=normalized_address,
            is_po_box=is_po_box,
            city=self.normalize_simple(row.get("city")),
            state=(row.get("state") or "").strip().upper(),
            zip5=(row.get("zip5") or "").strip()[:5],
            zip4=(row.get("zip4") or "").strip()[:4],
            country=(row.get("country") or "").strip().upper(),
            split=(row.get("split") or "").strip(),
            precinct=(row.get("precinct") or "").strip(),
            normalized_precinct=normalized_precinct,
            return_method=(row.get("return_method") or "").strip(),
            return_location_name=(row.get("return_location") or "").strip(),
            party=(row.get("party") or "").strip(),
            source_file=(row.get("source_file") or "").strip(),
            source_row=self.safe_int(row.get("source_row")),
        )

    # ------------------------------------------------------------------
    # PARCEL MATCHING
    # ------------------------------------------------------------------

    def match_parcels(self):
        address_index = self.build_parcel_address_index()
        new_matches = []
        created = 0
        unmatched = 0
        for turnout in VoterTurnoutRaw.objects.filter(parcel_match__isnull=True).iterator(
            chunk_size=2000
        ):
            if not turnout.normalized_address:
                unmatched += 1
                continue
            parcel = address_index.get(turnout.normalized_address)
            if not parcel:
                unmatched += 1
                continue
            new_matches.append(
                VoterParcelMatch(
                    turnout=turnout,
                    parcel=parcel,
                    match_type="address_exact",
                    confidence=0.9,
                    metadata={"normalized_address": turnout.normalized_address},
                )
            )
            if len(new_matches) >= 2000:
                VoterParcelMatch.objects.bulk_create(new_matches, batch_size=2000, ignore_conflicts=True)
                created += len(new_matches)
                new_matches = []

        if new_matches:
            VoterParcelMatch.objects.bulk_create(new_matches, batch_size=2000, ignore_conflicts=True)
            created += len(new_matches)

        return created, unmatched

    def build_parcel_address_index(self):
        index = {}
        qs = MasterParcel.objects.exclude(situs_address__isnull=True).exclude(situs_address="")
        for parcel in qs.iterator(chunk_size=5000):
            norm = self.normalize_address(parcel.situs_address)
            if not norm:
                continue
            index.setdefault(norm, parcel)
        return index

    # ------------------------------------------------------------------
    # TAXATION REPORT
    # ------------------------------------------------------------------

    def resolve_report_election(self, options):
        slug_value = options.get("election_slug")
        if slug_value:
            try:
                return VoterElection.objects.get(slug=slug_value)
            except VoterElection.DoesNotExist:
                self.stderr.write(self.style.WARNING(f"Election slug '{slug_value}' not found"))
                return None

        date_str = options.get("election_date")
        qs = VoterElection.objects.all()
        if date_str:
            try:
                target_date = datetime.strptime(date_str, "%Y-%m-%d").date()
            except ValueError as exc:
                raise CommandError(f"Invalid --election-date '{date_str}': {exc}") from exc
            qs = qs.filter(election_date=target_date)

        category = options.get("election_category")
        if category:
            qs = qs.filter(category__iexact=category)

        return qs.order_by("-election_date").first()

    def build_taxation_report(self, election, tax_threshold):
        TaxationWithoutRepresentation.objects.filter(election=election).delete()
        ballots_by_parcel = {
            row["parcel_id"]: row["count"]
            for row in VoterParcelMatch.objects.filter(turnout__election=election)
            .values("parcel_id")
            .annotate(count=Count("id"))
        }

        reports = []
        master_cache = {}
        flagged = 0
        hood_counts = Counter()
        total_tax = 0

        for history in ParcelHistory.objects.exclude(rows__isnull=True).only("parcel_number", "rows").iterator(
            chunk_size=1000
        ):
            parcel_number = history.parcel_number
            tax_year, tax_amount = self.extract_latest_tax(history.rows)
            if not tax_amount or tax_amount < tax_threshold:
                continue
            ballots = ballots_by_parcel.get(parcel_number, 0)
            if ballots:
                continue
            parcel = self.get_master_parcel(parcel_number, master_cache)
            if not parcel:
                continue
            metadata = {
                "neighborhood_code": parcel.hood_code,
                "city_district": parcel.city_district,
                "fire_district": parcel.fire_district,
                "school_district": parcel.school_district,
                "precinct": None,
            }
            reports.append(
                TaxationWithoutRepresentation(
                    parcel=parcel,
                    election=election,
                    tax_year=tax_year,
                    tax_amount=tax_amount,
                    ballots_cast=ballots,
                    flag_reason=(
                        f"Paid ${tax_amount:,} in taxes in {tax_year} with no recorded ballots for {election.name}"
                    ),
                    metadata=metadata,
                )
            )
            flagged += 1
            hood_counts[parcel.hood_code or "Unknown"] += 1
            total_tax += tax_amount

        if reports:
            TaxationWithoutRepresentation.objects.bulk_create(reports, batch_size=1000)

        top_hoods = ", ".join(f"{hood}: {count}" for hood, count in hood_counts.most_common(5))
        self.stdout.write(
            f"Flagged ${total_tax:,} in taxes across {flagged} parcels. Top neighborhoods: {top_hoods}"
        )
        return flagged

    def get_master_parcel(self, parcel_number, cache):
        if parcel_number in cache:
            return cache[parcel_number]
        try:
            parcel = MasterParcel.objects.get(pk=parcel_number)
        except MasterParcel.DoesNotExist:
            parcel = None
        cache[parcel_number] = parcel
        return parcel

    def extract_latest_tax(self, rows):
        latest = None
        if not isinstance(rows, list):
            return None, None
        for record in rows:
            if not isinstance(record, dict):
                continue
            raw_year = record.get("VALUE YEAR") or record.get("TAX YEAR")
            raw_tax = record.get("TAX") or record.get("PROPERTY TAX") or record.get("TOTAL TAX")
            if not raw_year or raw_tax is None:
                continue
            try:
                year = int(str(raw_year).strip())
            except ValueError:
                continue
            tax_value = self.parse_money(raw_tax)
            if tax_value is None:
                continue
            if not latest or year > latest[0]:
                latest = (year, tax_value)
        return latest if latest else (None, None)

    # ------------------------------------------------------------------
    # HELPERS
    # ------------------------------------------------------------------

    def normalize_simple(self, value):
        if not value:
            return ""
        return " ".join(str(value).strip().upper().split())

    def normalize_address(self, value):
        if not value:
            return ""
        upper = self.normalize_simple(value)
        cleaned = re.sub(r"[^A-Z0-9#/ ]", " ", upper)
        return " ".join(cleaned.split())

    def parse_datetime(self, value):
        if not value:
            return None
        try:
            return datetime.fromisoformat(value)
        except ValueError:
            return None

    def parse_money(self, raw):
        if raw is None:
            return None
        if isinstance(raw, (int, float)):
            return int(float(raw))
        cleaned = re.sub(r"[^0-9.]+", "", str(raw))
        if not cleaned:
            return None
        try:
            return int(round(float(cleaned)))
        except ValueError:
            return None

    def safe_int(self, value):
        if value in (None, ""):
            return None
        try:
            return int(value)
        except (ValueError, TypeError):
            return None
