# Generated by Django 5.2.7 on 2026-01-19 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jurisdiction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('state', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='LawDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_number', models.CharField(max_length=20)),
                ('title_name', models.CharField(max_length=255)),
                ('source_vendor', models.CharField(max_length=100)),
                ('effective_note', models.TextField(blank=True, null=True)),
                ('jurisdiction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='legal_code.jurisdiction')),
            ],
            options={
                'unique_together': {('jurisdiction', 'title_number')},
            },
        ),
        migrations.CreateModel(
            name='LawChapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter_number', models.CharField(max_length=20)),
                ('chapter_name', models.CharField(max_length=255)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='legal_code.lawdocument')),
            ],
            options={
                'unique_together': {('document', 'chapter_number')},
            },
        ),
        migrations.CreateModel(
            name='LawSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_id', models.CharField(max_length=50)),
                ('heading', models.CharField(max_length=500)),
                ('content', models.TextField()),
                ('history', models.JSONField(blank=True, default=list)),
                ('tables', models.JSONField(blank=True, default=list)),
                ('content_hash', models.CharField(db_index=True, max_length=64)),
                ('source_url', models.URLField()),
                ('scraped_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='legal_code.lawchapter')),
            ],
            options={
                'indexes': [models.Index(fields=['section_id'], name='legal_code__section_232be6_idx'), models.Index(fields=['content_hash'], name='legal_code__content_7871cd_idx')],
            },
        ),
    ]
