# Generated by Django 5.2.7 on 2026-01-19 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("legal_code", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="JurisdictionAlias",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("alias", models.CharField(max_length=200)),
                (
                    "alias_normalized",
                    models.CharField(
                        db_index=True,
                        max_length=200,
                        unique=True,
                    ),
                ),
                ("source", models.CharField(blank=True, max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "jurisdiction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="aliases",
                        to="legal_code.jurisdiction",
                    ),
                ),
            ],
            options={
                "ordering": ["alias_normalized"],
            },
        ),
    ]
