# Generated by Django 5.2.7 on 2026-01-20 16:09

import django.db.models.deletion
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legal_code', '0002_jurisdictionalias'),
    ]

    operations = [
        migrations.CreateModel(
            name='LawSectionChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('law_section_ref', models.CharField(db_index=True, max_length=50)),
                ('heading', models.CharField(blank=True, max_length=500)),
                ('source_url', models.URLField()),
                ('chunk_index', models.PositiveIntegerField(default=0)),
                ('content', models.TextField()),
                ('content_hash', models.CharField(db_index=True, max_length=64)),
                ('embedding_model', models.CharField(max_length=100)),
                ('embedding', pgvector.django.vector.VectorField(blank=True, dimensions=1536, null=True)),
                ('embedded_at', models.DateTimeField(blank=True, null=True)),
                ('jurisdiction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='legal_code.jurisdiction')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='legal_code.lawsection')),
            ],
            options={
                'indexes': [models.Index(fields=['jurisdiction', 'section_id'], name='legal_code__jurisdi_91b4b0_idx'), models.Index(fields=['content_hash'], name='legal_code__content_31e13e_idx')],
                'unique_together': {('section', 'chunk_index', 'embedding_model')},
            },
        ),
    ]
