# Generated by Django 5.2.7 on 2026-01-20 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legal_code', '0003_lawsectionchunk'),
    ]

    operations = [
        migrations.AddField(
            model_name='lawsectionchunk',
            name='lane_scores',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lawsectionchunk',
            name='lanes_classified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
