# Generated by Django 5.2.7 on 2026-01-21 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legal_code', '0004_lawsectionchunk_lane_scores_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lawchapter',
            name='code_set',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
