# Generated by Django 5.2.7 on 2025-12-15 15:07

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CrawlLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=100)),
                ('scope', models.CharField(blank=True, max_length=200, null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('success_count', models.IntegerField(default=0)),
                ('skip_count', models.IntegerField(default=0)),
                ('error_count', models.IntegerField(default=0)),
                ('api_calls', models.IntegerField(default=0)),
                ('est_cost_usd', models.FloatField(default=0.0)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='UrlDiscovery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=255, unique=True)),
                ('result_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hit_count', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_id', models.CharField(db_index=True, max_length=400, unique=True)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('address', models.TextField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('website', models.URLField(blank=True, max_length=2000, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('menu_url', models.URLField(blank=True, max_length=2000, null=True)),
                ('url_checked_at', models.DateTimeField(blank=True, null=True)),
                ('url_source', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.CharField(blank=True, max_length=500, null=True)),
                ('cuisine', models.CharField(blank=True, max_length=100, null=True)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('review_count', models.IntegerField(default=0)),
                ('sentiment_score', models.FloatField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326)),
                ('embedding', pgvector.django.vector.VectorField(blank=True, dimensions=1536, null=True)),
                ('summary', models.TextField(blank=True, null=True)),
                ('keywords', models.JSONField(blank=True, null=True)),
                ('source', models.CharField(default='outscraper', max_length=50)),
                ('last_review_date', models.DateTimeField(blank=True, null=True)),
                ('avg_review_gap_days', models.FloatField(blank=True, null=True)),
                ('next_fetch_at', models.DateTimeField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('hours', models.JSONField(blank=True, null=True)),
                ('about', models.JSONField(blank=True, null=True)),
                ('price_range', models.CharField(blank=True, max_length=20, null=True)),
                ('logo_url', models.URLField(blank=True, max_length=2000, null=True)),
                ('photo_url', models.URLField(blank=True, max_length=2000, null=True)),
                ('street_view', models.URLField(blank=True, max_length=2000, null=True)),
                ('location_link', models.URLField(blank=True, max_length=2000, null=True)),
                ('booking_appointment_link', models.URLField(blank=True, max_length=2000, null=True)),
                ('owner_link', models.URLField(blank=True, max_length=2000, null=True)),
                ('reviews_url', models.URLField(blank=True, max_length=2000, null=True)),
                ('reservation_links', models.JSONField(blank=True, null=True)),
                ('order_links', models.JSONField(blank=True, null=True)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['city', 'category'], name='gastronet_r_city_ee9961_idx'), models.Index(fields=['city', 'active'], name='gastronet_r_city_8e1d35_idx'), models.Index(fields=['next_fetch_at'], name='gastronet_r_next_fe_eb2f1f_idx')],
            },
        ),
        migrations.CreateModel(
            name='MenuSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
                ('source_url', models.URLField()),
                ('text', models.TextField()),
                ('hash', models.CharField(max_length=64)),
                ('parsed_json', models.JSONField(blank=True, null=True)),
                ('summary', models.TextField(blank=True, null=True)),
                ('render_method', models.CharField(blank=True, max_length=50, null=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_snapshots', to='gastronet.restaurant')),
            ],
        ),
        migrations.CreateModel(
            name='MenuAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tried_url', models.URLField(blank=True, null=True)),
                ('source', models.CharField(blank=True, max_length=50, null=True)),
                ('found', models.BooleanField(default=False)),
                ('parsed', models.BooleanField(default=False)),
                ('status', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_attempts', to='gastronet.restaurant')),
            ],
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_url', models.URLField(max_length=500)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('section', models.CharField(blank=True, max_length=255)),
                ('dietary_tags', models.JSONField(blank=True, default=list)),
                ('currency', models.CharField(default='USD', max_length=8)),
                ('scraped_at', models.DateTimeField(auto_now_add=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='gastronet.restaurant')),
            ],
            options={
                'unique_together': {('restaurant', 'source_url', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=50)),
                ('review_id', models.CharField(db_index=True, max_length=200)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField()),
                ('scraped_at', models.DateTimeField(auto_now_add=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='gastronet.restaurant')),
            ],
            options={
                'indexes': [models.Index(fields=['restaurant', 'created_at'], name='gastronet_r_restaur_d01639_idx')],
                'unique_together': {('restaurant', 'source', 'review_id')},
            },
        ),
    ]
