# Generated by Django 5.2.7 on 2025-12-21 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastronet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='last_crawled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='menu_found',
            field=models.BooleanField(default=False),
        ),
    ]
