# Generated by Django 5.2.7 on 2025-12-23 02:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastronet', '0002_restaurant_last_crawled_at_restaurant_menu_found'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewEnrichment',
            fields=[
                ('review', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='enrichment', serialize=False, to='gastronet.review')),
                ('polarity', models.CharField(blank=True, max_length=16, null=True)),
                ('sentiment_score', models.FloatField(blank=True, null=True)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('language', models.CharField(blank=True, max_length=16, null=True)),
                ('aspects', models.JSONField(blank=True, null=True)),
                ('aspect_sentiment', models.JSONField(blank=True, null=True)),
                ('dish_mentions', models.JSONField(blank=True, null=True)),
                ('cuisine_signals', models.JSONField(blank=True, null=True)),
                ('flags', models.JSONField(blank=True, null=True)),
                ('short_excerpts', models.JSONField(blank=True, null=True)),
                ('model', models.CharField(blank=True, max_length=64, null=True)),
                ('schema_version', models.CharField(default='v1', max_length=32)),
                ('prompt_version', models.CharField(default='v1', max_length=32)),
                ('batch_id', models.CharField(blank=True, max_length=64, null=True)),
                ('custom_id', models.CharField(blank=True, max_length=128, null=True)),
                ('raw_response', models.JSONField(blank=True, null=True)),
                ('enriched_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
