# Generated by Django 5.2.7 on 2025-12-23 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastronet', '0004_batchjob_reviewenrichment_notes'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='batchjob',
            new_name='gastronet_b_job_typ_840254_idx',
            old_name='gastronet_batchjob_job_type_status_idx',
        ),
        migrations.RenameIndex(
            model_name='batchjob',
            new_name='gastronet_b_status_1b5f32_idx',
            old_name='gastronet_batchjob_status_applied_at_idx',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='yelp_id',
            field=models.CharField(max_length=400, null=True, unique=True),
        ),
    ]
