# Generated by Django 5.2.7 on 2025-12-23 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastronet', '0005_rename_gastronet_batchjob_job_type_status_idx_gastronet_b_job_typ_840254_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='analysis_payload',
            field=models.JSONField(default=dict),
        ),
    ]
