# Generated by Django 5.2.7 on 2025-12-23 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gastronet', '0006_review_analysis_payload'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BatchJob',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='last_crawled_at',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='menu_found',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='yelp_id',
        ),
        migrations.DeleteModel(
            name='ReviewEnrichment',
        ),
    ]
