# Generated by Django 5.2.7 on 2025-12-26 16:00
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gastronet", "0008_restore_restaurant_last_crawled_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="RestaurantCrawlLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("task", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "restaurant",
                    models.ForeignKey(
                        on_delete=models.deletion.CASCADE,
                        related_name="task_crawl_logs",
                        to="gastronet.restaurant",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="restaurantcrawllog",
            constraint=models.UniqueConstraint(
                fields=["restaurant", "task"], name="gastronet_restaurant_task_unique"
            ),
        ),
    ]
