# Generated by Django 5.2.7 on 2025-12-23 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gastronet', '0009_create_restaurant_crawl_log'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='restaurantcrawllog',
            name='gastronet_restaurant_task_unique',
        ),
        migrations.AlterUniqueTogether(
            name='restaurantcrawllog',
            unique_together={('restaurant', 'task')},
        ),
    ]
