# Generated by Django 5.2.7 on 2025-12-24 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastronet', '0010_remove_restaurantcrawllog_gastronet_restaurant_task_unique_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='no_menu',
            field=models.BooleanField(default=False),
        ),
    ]
