# Generated by Django 5.2.7 on 2025-12-26 17:05

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastronet', '0011_restaurant_no_menu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menusnapshot',
            name='restaurant',
        ),
        migrations.CreateModel(
            name='ReviewEnrichment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentiment_overall', models.CharField(blank=True, max_length=10, null=True)),
                ('sentiment_score', models.FloatField(blank=True, null=True)),
                ('menu_items', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, help_text='Extracted menu items (normalized when possible, raw if not matched)', size=None)),
                ('menu_item_sentiments', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=10), blank=True, default=list, help_text='Sentiments for each menu item', size=None)),
                ('staff_names', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, size=None)),
                ('staff_roles', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, size=None)),
                ('staff_sentiments', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=10), blank=True, default=list, size=None)),
                ('value_for_money', models.CharField(blank=True, max_length=10, null=True)),
                ('ambience', models.CharField(blank=True, max_length=10, null=True)),
                ('service_speed', models.CharField(blank=True, max_length=20, null=True)),
                ('service_attitude', models.CharField(blank=True, max_length=20, null=True)),
                ('wait_time_description', models.CharField(blank=True, max_length=255, null=True)),
                ('intents', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, size=None)),
                ('highlights', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=500), blank=True, default=list, size=None)),
                ('issue_categories', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, size=None)),
                ('issue_descriptions', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=500), blank=True, default=list, size=None)),
                ('entities', models.JSONField(blank=True, default=dict)),
                ('key_phrases', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, size=None)),
                ('review', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='enrichment', to='gastronet.review')),
            ],
        ),
        migrations.DeleteModel(
            name='MenuAttempt',
        ),
        migrations.DeleteModel(
            name='MenuSnapshot',
        ),
    ]
