# Generated by Django 5.2.7 on 2026-01-01 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gastronet", "0012_remove_menusnapshot_restaurant_reviewenrichment_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="crawllog",
            name="response_details",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
