# Generated by Django 5.2.7 on 2025-12-30 13:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastronet', '0017_remove_google_place_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tried_url', models.URLField(blank=True, null=True)),
                ('source', models.CharField(blank=True, max_length=50, null=True)),
                ('found', models.BooleanField(default=False)),
                ('parsed', models.BooleanField(default=False)),
                ('status', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_attempts', to='gastronet.restaurant')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['restaurant', 'created_at'], name='gastronet_m_restaur_7a66a6_idx')],
            },
        ),
        migrations.CreateModel(
            name='MenuSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
                ('source_url', models.URLField()),
                ('text', models.TextField()),
                ('hash', models.CharField(max_length=64)),
                ('parsed_json', models.JSONField(blank=True, null=True)),
                ('summary', models.TextField(blank=True, null=True)),
                ('render_method', models.CharField(blank=True, max_length=50, null=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_snapshots', to='gastronet.restaurant')),
            ],
            options={
                'ordering': ['-fetched_at'],
                'indexes': [models.Index(fields=['restaurant', 'fetched_at'], name='gastronet_m_restaur_ca5a20_idx')],
            },
        ),
    ]
