# Generated by Django 5.2.7 on 2026-01-04 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastronet', '0019_restaurant_profiles'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='enrichment_v1',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
