# Generated by Django 5.2.7 on 2026-01-04 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastronet', '0020_menuitem_enrichment_v1'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='menu_profile_v1',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
