# Generated by Django 5.2.7 on 2026-01-05 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastronet', '0021_restaurant_menu_profile_v1'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='community_acceptance_v1',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
