# Generated by Django 5.2.7 on 2026-01-05 00:00

import uuid
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("gastronet", "0022_restaurant_community_acceptance_v1"),
    ]

    operations = [
        migrations.CreateModel(
            name="SkagitDishIdea",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("direction", models.CharField(max_length=40)),
                ("identity_version", models.CharField(max_length=20)),
                ("payload", models.JSONField()),
                ("created_at", models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
