# Generated by Django 5.2.7 on 2026-01-03 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('slug', models.SlugField(blank=True, max_length=80)),
                ('card_type', models.CharField(choices=[('YOUTUBE', 'YouTube'), ('ANIMAL_SOUND', 'Animal Sound'), ('PHOTO', 'Photo'), ('DRAW', 'Draw'), ('PLACEHOLDER', 'Placeholder')], max_length=20)),
                ('direction', models.CharField(choices=[('up', 'Up'), ('down', 'Down'), ('left', 'Left'), ('right', 'Right'), ('sequence', 'Sequence')], default='up', max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='kidslab/images')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='kidslab/images')),
                ('audio', models.FileField(blank=True, null=True, upload_to='kidslab/audio')),
                ('youtube_url', models.URLField(blank=True, null=True)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['direction', 'order', 'title'],
            },
        ),
    ]
