# Generated by Django 5.2.7 on 2026-01-03 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kidslab', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='card_type',
            field=models.CharField(choices=[('YOUTUBE', 'YouTube'), ('ANIMAL_SOUND', 'Animal Sound'), ('PHOTO', 'Photo'), ('DRAW', 'Draw'), ('PLACEHOLDER', 'Placeholder'), ('MAZE', 'Maze')], max_length=20),
        ),
    ]
