# Generated by Django 5.2.7 on 2026-01-29 14:13

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompetitionAnalysisJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('place_id', models.CharField(max_length=255)),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('address', models.CharField(blank=True, default='', max_length=512)),
                ('status', models.CharField(choices=[('scouting', 'Scouting subject'), ('ready', 'Ready for deep analysis'), ('deep_pending', 'Queued for deep analysis'), ('deep_running', 'Running deep analysis'), ('completed', 'Completed'), ('failed', 'Failed')], default='scouting', max_length=32)),
                ('progress_log', models.JSONField(blank=True, default=list)),
                ('subject_payload', models.JSONField(blank=True, null=True)),
                ('vetted_competitors', models.JSONField(blank=True, null=True)),
                ('final_payload', models.JSONField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
