# Generated by Django 5.2.7 on 2026-01-29 23:17

import agent.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_session_id', models.CharField(help_text='Stripe checkout session ID that created the job.', max_length=255, unique=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('FAILED', 'Failed')], default='PENDING', help_text='Stripe payment lifecycle state.', max_length=16)),
                ('amount_usd', models.DecimalField(blank=True, decimal_places=2, help_text='Captured amount (if available).', max_digits=10, null=True)),
                ('paid_at', models.DateTimeField(blank=True, help_text='Timestamp provided by Stripe when payment went through.', null=True)),
                ('note', models.TextField(blank=True, help_text='Optional note such as webhook ID or failure reason.')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Record creation ts.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When record last changed.')),
            ],
        ),
        migrations.CreateModel(
            name='RestaurantReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text='Unpredictable slug for shareable link.', max_length=64, unique=True)),
                ('payload', models.TextField(help_text='Serialized FinalReportPayload JSON.')),
                ('generated_at', models.DateTimeField(auto_now_add=True, help_text='When payload built.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When payload changed last.')),
            ],
        ),
        migrations.CreateModel(
            name='RestaurantReportCheckpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.CharField(help_text='Name of the pipeline step popoulating this checkpoint.', max_length=64)),
                ('payload', models.TextField(help_text='Serialized JSON payload produced at the step.')),
                ('schema_version', models.CharField(help_text='Schema version to validate payload against.', max_length=16)),
                ('checksum', models.CharField(help_text='SHA256 of the payload string to detect corruption.', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Create timestamp.')),
            ],
            options={
                'ordering': ['job', 'step', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RestaurantReportJob',
            fields=[
                ('id', models.CharField(default=agent.models._generate_job_id, editable=False, help_text='Deterministic slug surfaced to the customer.', max_length=32, primary_key=True, serialize=False)),
                ('place_id', models.CharField(help_text='Google Places place_id.', max_length=255)),
                ('place_name', models.CharField(help_text='Cached restaurant name.', max_length=255)),
                ('address', models.CharField(help_text='Formatted address snapshot.', max_length=512)),
                ('status', models.CharField(choices=[('CREATED', 'Created'), ('PAID', 'Paid'), ('RUNNING', 'Running'), ('FAILED', 'Failed'), ('COMPLETED', 'Completed')], default='CREATED', help_text='Current lifecycle state of the job.', max_length=16)),
                ('progress_percent', models.PositiveSmallIntegerField(default=0, help_text='Estimated completion percent (0-100).')),
                ('current_step', models.CharField(blank=True, help_text='Last completed orchestrator step name.', max_length=64)),
                ('error_code', models.CharField(blank=True, help_text='Optional machine-friendly failure code.', max_length=32)),
                ('error_message', models.TextField(blank=True, help_text='Human-readable description when failures occur.')),
                ('progress_log', models.JSONField(default=list, help_text='JSON list of {ts,message} entries describing pipeline events.')),
                ('subject_payload', models.JSONField(blank=True, help_text='Latest subject data (seed for deeper analysis).', null=True)),
                ('vetted_competitors', models.JSONField(blank=True, help_text='Vetted competitor list produced during scouting.', null=True)),
                ('final_payload', models.JSONField(blank=True, help_text='Serialized FinalReportPayload for rendering and sharing.', null=True)),
                ('cost_usd', models.DecimalField(blank=True, decimal_places=2, help_text='Estimated third-party spend so the job can cap costs.', max_digits=10, null=True)),
                ('started_at', models.DateTimeField(blank=True, help_text='When the first orchestrator step started.', null=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='When job finished (either success or failure).', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Record creation ts.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last metadata update.')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='CompetitionAnalysisJob',
        ),
        migrations.AddField(
            model_name='restaurantreportcheckpoint',
            name='job',
            field=models.ForeignKey(help_text='Parent job that owns this checkpoint.', on_delete=django.db.models.deletion.CASCADE, related_name='checkpoints', to='agent.restaurantreportjob'),
        ),
        migrations.AddField(
            model_name='restaurantreport',
            name='job',
            field=models.OneToOneField(help_text='Job that produced this report.', on_delete=django.db.models.deletion.CASCADE, related_name='report', to='agent.restaurantreportjob'),
        ),
        migrations.AddField(
            model_name='paymentrecord',
            name='job',
            field=models.OneToOneField(help_text='Job awaiting payment.', on_delete=django.db.models.deletion.CASCADE, related_name='payment_record', to='agent.restaurantreportjob'),
        ),
        migrations.AlterUniqueTogether(
            name='restaurantreportcheckpoint',
            unique_together={('job', 'step')},
        ),
    ]
