# Generated by Django 4.2.7 on 2024-11-25 21:28

from django.db import migrations

SQL_CREATE_SCHEMA_AND_FUNCTION = """
CREATE SCHEMA IF NOT EXISTS agent;

CREATE OR REPLACE FUNCTION agent.parcel_bundle_v1(p_parcel_id TEXT)
RETURNS JSONB AS $$
DECLARE
    bundle JSONB;
BEGIN
    SELECT jsonb_build_object(
        'parcel', to_jsonb(mp.*),
        'geometry', (SELECT ST_AsGeoJSON(pg.geom)::jsonb FROM openskagit_parcelgeometry pg WHERE pg.parcel_id = mp.parcel_number),
        'planning_facts', (SELECT to_jsonb(ppf.*) FROM parcel_planning_facts ppf WHERE ppf.parcel_id = mp.parcel_number),
        'assessments', (
            SELECT to_jsonb(a.*)
            FROM assessor a
            WHERE a.parcel_number = mp.parcel_number
            ORDER BY a.roll_id DESC NULLS LAST
            LIMIT 1
        ),
        'sales', (
            SELECT jsonb_agg(to_jsonb(s.*) ORDER BY s.sale_date DESC)
            FROM sales s
            WHERE s.parcel_number = mp.parcel_number
            LIMIT 10
        ),
        'zoning_tags', (
             SELECT jsonb_build_array(ppf.zone_code)
             FROM parcel_planning_facts ppf
             WHERE ppf.parcel_id = mp.parcel_number AND ppf.zone_code IS NOT NULL
        ),
        'overlay_tags', (
            SELECT jsonb_agg(DISTINCT key)
            FROM (
                SELECT CASE WHEN in_wetland THEN 'in_wetland' END AS key FROM parcel_planning_facts WHERE parcel_id = mp.parcel_number AND in_wetland
                UNION ALL
                SELECT CASE WHEN in_stream_buffer THEN 'in_stream_buffer' END FROM parcel_planning_facts WHERE parcel_id = mp.parcel_number AND in_stream_buffer
                UNION ALL
                SELECT CASE WHEN in_shoreline_jurisdiction THEN 'in_shoreline_jurisdiction' END FROM parcel_planning_facts WHERE parcel_id = mp.parcel_number AND in_shoreline_jurisdiction
                UNION ALL
                SELECT CASE WHEN in_flood_zone THEN 'in_flood_zone' END FROM parcel_planning_facts WHERE parcel_id = mp.parcel_number AND in_flood_zone
                UNION ALL
                SELECT CASE WHEN in_sfha THEN 'in_sfha' END FROM parcel_planning_facts WHERE parcel_id = mp.parcel_number AND in_sfha
                UNION ALL
                SELECT CASE WHEN in_floodway THEN 'in_floodway' END FROM parcel_planning_facts WHERE parcel_id = mp.parcel_number AND in_floodway
            ) AS tags
            WHERE key IS NOT NULL
        ),
        'sources', jsonb_build_object(
            'parcel_table', 'master_parcel',
            'geom_table', 'openskagit_parcelgeometry',
            'planning_facts_table', 'parcel_planning_facts',
            'assessments_table', 'assessor',
            'sales_table', 'sales'
        )
    )
    INTO bundle
    FROM master_parcel mp
    WHERE mp.parcel_number = p_parcel_id;

    RETURN bundle;
END;
$$ LANGUAGE plpgsql;
"""

SQL_DROP_FUNCTION = """
DROP FUNCTION IF EXISTS agent.parcel_bundle_v1(TEXT);
DROP SCHEMA IF EXISTS agent CASCADE;
"""

class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0002_auto_20241121_0434'),
    ]

    operations = [
        migrations.RunSQL(SQL_CREATE_SCHEMA_AND_FUNCTION, SQL_DROP_FUNCTION),
    ]