# Generated by Django 5.2.7 on 2025-12-15 22:10

import django.contrib.gis.db.models.fields
import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference_data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferenceZoningEnvelope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=50)),
                ('jurisdiction', models.CharField(max_length=100)),
                ('county_name', models.CharField(blank=True, max_length=100, null=True)),
                ('zone_code', models.CharField(max_length=100)),
                ('zone_name', models.CharField(blank=True, max_length=255, null=True)),
                ('zoning_general_class', models.CharField(blank=True, max_length=30, null=True)),
                ('zoning_specific_class', models.CharField(blank=True, max_length=100, null=True)),
                ('allows_residential', models.BooleanField(blank=True, null=True)),
                ('allows_duplex', models.BooleanField(blank=True, null=True)),
                ('allows_multifamily', models.BooleanField(blank=True, null=True)),
                ('allows_retail', models.BooleanField(blank=True, null=True)),
                ('allows_office', models.BooleanField(blank=True, null=True)),
                ('allows_industrial', models.BooleanField(blank=True, null=True)),
                ('allows_heavy_industrial', models.BooleanField(blank=True, null=True)),
                ('allows_agriculture', models.BooleanField(blank=True, null=True)),
                ('allows_forestry', models.BooleanField(blank=True, null=True)),
                ('allows_green_energy', models.BooleanField(blank=True, null=True)),
                ('allows_data_center', models.BooleanField(blank=True, null=True)),
                ('allows_warehouse', models.BooleanField(blank=True, null=True)),
                ('min_lot_size_sqft', models.FloatField(blank=True, null=True)),
                ('max_lot_coverage_pct', models.FloatField(blank=True, null=True)),
                ('max_height_ft', models.FloatField(blank=True, null=True)),
                ('max_stories', models.FloatField(blank=True, null=True)),
                ('max_far', models.FloatField(blank=True, null=True)),
                ('min_far', models.FloatField(blank=True, null=True)),
                ('max_density_du_ac', models.FloatField(blank=True, null=True)),
                ('min_density_du_ac', models.FloatField(blank=True, null=True)),
                ('max_units_per_lot', models.IntegerField(blank=True, null=True)),
                ('adus_allowed_count', models.IntegerField(blank=True, null=True)),
                ('adu_owner_occupancy_required', models.BooleanField(blank=True, null=True)),
                ('parking_min_residential', models.FloatField(blank=True, null=True)),
                ('parking_min_middle_housing', models.FloatField(blank=True, null=True)),
                ('parking_min_apartment', models.FloatField(blank=True, null=True)),
                ('parking_min_retail', models.FloatField(blank=True, null=True)),
                ('parking_min_restaurant', models.FloatField(blank=True, null=True)),
                ('parking_min_office', models.FloatField(blank=True, null=True)),
                ('reference_url', models.URLField(blank=True, max_length=500, null=True)),
                ('source_last_verified', models.DateField(blank=True, null=True)),
                ('geometry', django.contrib.gis.db.models.fields.MultiPolygonField(srid=3857)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'reference_zoning_envelope',
                'indexes': [models.Index(fields=['jurisdiction'], name='reference_z_jurisdi_8160de_idx'), models.Index(fields=['zone_code'], name='reference_z_zone_co_bbab36_idx'), django.contrib.postgres.indexes.GistIndex(fields=['geometry'], name='reference_z_geometr_eeadcf_gist')],
            },
        ),
    ]
