# Generated by Django 5.2.7 on 2025-12-19 16:19

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference_data', '0002_referencezoningenvelope'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferenceZoningZone',
            fields=[
                ('objectid', models.IntegerField(primary_key=True, serialize=False)),
                ('geoid', models.TextField()),
                ('jurisdiction', models.TextField()),
                ('countyfp', models.TextField()),
                ('countyname', models.TextField()),
                ('zoneid', models.TextField()),
                ('zonename', models.TextField()),
                ('wazazonegeneral', models.TextField()),
                ('wazazonespecific', models.TextField()),
                ('useresidential', models.TextField()),
                ('useretail', models.TextField()),
                ('useoffice', models.TextField()),
                ('usemanufacturing', models.TextField()),
                ('useheavyindustrial', models.TextField()),
                ('usegreenenergy', models.TextField()),
                ('usedatacenter', models.TextField()),
                ('usewarehouse', models.TextField()),
                ('useforestry', models.TextField()),
                ('useagriculture', models.TextField()),
                ('usemining', models.TextField()),
                ('dimmaxheight', models.FloatField(blank=True, null=True)),
                ('dimmaxstories', models.FloatField(blank=True, null=True)),
                ('dimbonusmaxheight', models.FloatField(blank=True, null=True)),
                ('dimbonusmaxstories', models.FloatField(blank=True, null=True)),
                ('dimminheight', models.FloatField(blank=True, null=True)),
                ('dimminstories', models.FloatField(blank=True, null=True)),
                ('dimmaxfar', models.FloatField(blank=True, null=True)),
                ('dimbonusmaxfar', models.FloatField(blank=True, null=True)),
                ('dimminfar', models.FloatField(blank=True, null=True)),
                ('dimmaxlotcoverbuildings', models.FloatField(blank=True, null=True)),
                ('dimmaxlotcoverbuildingsandimpsu', models.FloatField(blank=True, null=True)),
                ('denminlotsizesqft', models.FloatField(blank=True, null=True)),
                ('denmaxdensity', models.FloatField(blank=True, null=True)),
                ('denbonusmaxdensity', models.FloatField(blank=True, null=True)),
                ('denmindensity', models.FloatField(blank=True, null=True)),
                ('denmaxprimaryunitsperlot', models.FloatField(blank=True, null=True)),
                ('denbonusmaxprimaryunitsperlot', models.FloatField(blank=True, null=True)),
                ('dennumadusallowed', models.FloatField(blank=True, null=True)),
                ('denaduoccupancyrequirement', models.TextField()),
                ('bonusah', models.TextField()),
                ('bonustdr', models.TextField()),
                ('minparkingressur', models.FloatField(blank=True, null=True)),
                ('minparkingresmh', models.FloatField(blank=True, null=True)),
                ('minparkingresapt', models.FloatField(blank=True, null=True)),
                ('minparkingretail', models.FloatField(blank=True, null=True)),
                ('minparkingrestaraunt', models.FloatField(blank=True, null=True)),
                ('minparkingoffice', models.FloatField(blank=True, null=True)),
                ('minparkingresmeasure_deprecated', models.TextField()),
                ('minparkingresidential_deprecate', models.FloatField(blank=True, null=True)),
                ('info', models.TextField()),
                ('referenceurl', models.TextField()),
                ('wazaspatialnormalizationdate', models.DateTimeField(blank=True, null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=2926)),
                ('shape_area', models.FloatField(blank=True, db_column='shape__area', null=True)),
                ('shape_length', models.FloatField(blank=True, db_column='shape__length', null=True)),
            ],
            options={
                'db_table': 'reference_zoning_zones',
            },
        ),
        migrations.DeleteModel(
            name='ReferenceDataImportLog',
        ),
        migrations.DeleteModel(
            name='ReferenceZoningEnvelope',
        ),
        migrations.AddIndex(
            model_name='referencezoningzone',
            index=models.Index(fields=['zoneid'], name='reference_z_zoneid_26c278_idx'),
        ),
        migrations.AddIndex(
            model_name='referencezoningzone',
            index=models.Index(fields=['jurisdiction'], name='reference_z_jurisdi_b8360b_idx'),
        ),
        migrations.AddIndex(
            model_name='referencezoningzone',
            index=models.Index(fields=['countyfp'], name='reference_z_countyf_5e3b39_idx'),
        ),
    ]
