# Generated by Django 5.2.7 on 2026-03-27 21:04

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GISSourceSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_url', models.URLField(max_length=2000)),
                ('normalized_url', models.URLField(blank=True, max_length=2000)),
                ('source_type_detected', models.CharField(choices=[('arcgis_feature_service_root', 'ArcGIS FeatureServer root'), ('arcgis_feature_layer', 'ArcGIS FeatureServer layer'), ('arcgis_map_service_root', 'ArcGIS MapServer root'), ('arcgis_map_layer', 'ArcGIS MapServer layer'), ('arcgis_hub_page', 'ArcGIS Hub / Open Data page'), ('arcgis_item_page', 'ArcGIS item page'), ('map_viewer_page', 'Map viewer page'), ('unknown', 'Unknown')], db_index=True, default='unknown', max_length=64)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('inspecting', 'Inspecting'), ('inspected', 'Inspected'), ('failed', 'Failed')], db_index=True, default='pending', max_length=24)),
                ('notes', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('inspected_at', models.DateTimeField(blank=True, null=True)),
                ('error_text', models.TextField(blank=True)),
                ('raw_summary_json', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='GISDiscoveredLayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discovered_from_url', models.URLField(blank=True, max_length=2000)),
                ('service_root_url', models.URLField(blank=True, max_length=2000)),
                ('layer_url', models.URLField(max_length=2000)),
                ('source_org', models.CharField(blank=True, max_length=255)),
                ('service_type', models.CharField(blank=True, max_length=32)),
                ('layer_id', models.IntegerField(blank=True, null=True)),
                ('layer_name', models.CharField(blank=True, max_length=255)),
                ('category', models.CharField(choices=[('parcels', 'Parcels'), ('addresses', 'Addresses'), ('zoning', 'Zoning'), ('future_land_use', 'Future Land Use'), ('city_limits', 'City Limits'), ('wards', 'Wards'), ('precincts', 'Precincts'), ('flood', 'Flood'), ('wetlands', 'Wetlands'), ('shoreline', 'Shoreline'), ('critical_areas', 'Critical Areas'), ('agriculture', 'Agriculture'), ('roads', 'Roads'), ('utilities', 'Utilities'), ('public_facilities', 'Public Facilities'), ('parks', 'Parks'), ('hazards', 'Hazards'), ('boundaries', 'Boundaries'), ('other', 'Other')], default='other', max_length=64)),
                ('geometry_type', models.CharField(blank=True, max_length=64)),
                ('id_field', models.CharField(blank=True, max_length=128)),
                ('auth_type', models.CharField(choices=[('none', 'None'), ('token_required', 'Token required'), ('unknown', 'Unknown')], default='unknown', max_length=32)),
                ('coverage', models.CharField(choices=[('countywide', 'Countywide'), ('municipal', 'Municipal'), ('statewide', 'Statewide'), ('national', 'National'), ('partial', 'Partial'), ('unknown', 'Unknown')], default='unknown', max_length=32)),
                ('skagit_relevance', models.CharField(choices=[('direct', 'Direct'), ('partial', 'Partial'), ('contextual', 'Contextual'), ('irrelevant', 'Irrelevant'), ('duplicate', 'Duplicate'), ('unknown', 'Unknown')], default='unknown', max_length=32)),
                ('usability', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low'), ('reject', 'Reject')], default='low', max_length=16)),
                ('qualification_status', models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='draft', max_length=16)),
                ('notes', models.TextField(blank=True)),
                ('metadata_json', models.JSONField(blank=True, default=dict)),
                ('fields_json', models.JSONField(blank=True, default=list)),
                ('capabilities_json', models.JSONField(blank=True, default=dict)),
                ('qualification_results_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discovered_layers', to='gis_registry.gissourcesubmission')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GISLayerManifest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=128, unique=True, validators=[django.core.validators.RegexValidator(message='Use snake_case for manifest keys.', regex='^[a-z0-9_]+$')])),
                ('label', models.CharField(max_length=255)),
                ('source_org', models.CharField(blank=True, max_length=255)),
                ('category', models.CharField(choices=[('parcels', 'Parcels'), ('addresses', 'Addresses'), ('zoning', 'Zoning'), ('future_land_use', 'Future Land Use'), ('city_limits', 'City Limits'), ('wards', 'Wards'), ('precincts', 'Precincts'), ('flood', 'Flood'), ('wetlands', 'Wetlands'), ('shoreline', 'Shoreline'), ('critical_areas', 'Critical Areas'), ('agriculture', 'Agriculture'), ('roads', 'Roads'), ('utilities', 'Utilities'), ('public_facilities', 'Public Facilities'), ('parks', 'Parks'), ('hazards', 'Hazards'), ('boundaries', 'Boundaries'), ('other', 'Other')], db_index=True, default='other', max_length=64)),
                ('service_type', models.CharField(blank=True, max_length=32)),
                ('service_root_url', models.URLField(blank=True, max_length=2000)),
                ('layer_url', models.URLField(max_length=2000, unique=True)),
                ('layer_id', models.IntegerField(blank=True, null=True)),
                ('layer_name', models.CharField(blank=True, max_length=255)),
                ('geometry_type', models.CharField(blank=True, max_length=64)),
                ('id_field', models.CharField(blank=True, max_length=128)),
                ('default_fields_json', models.JSONField(blank=True, default=list)),
                ('allowed_fields_sample_json', models.JSONField(blank=True, default=list)),
                ('queryable', models.BooleanField(default=False)),
                ('supports_geometry', models.BooleanField(default=False)),
                ('supports_where', models.BooleanField(default=False)),
                ('supports_pagination', models.BooleanField(default=False)),
                ('supports_ids_only', models.BooleanField(default=False)),
                ('supports_count_only', models.BooleanField(default=False)),
                ('max_record_count', models.IntegerField(blank=True, null=True)),
                ('auth_type', models.CharField(choices=[('none', 'None'), ('token_required', 'Token required'), ('unknown', 'Unknown')], default='unknown', max_length=32)),
                ('coverage', models.CharField(choices=[('countywide', 'Countywide'), ('municipal', 'Municipal'), ('statewide', 'Statewide'), ('national', 'National'), ('partial', 'Partial'), ('unknown', 'Unknown')], default='unknown', max_length=32)),
                ('skagit_relevance', models.CharField(choices=[('direct', 'Direct'), ('partial', 'Partial'), ('contextual', 'Contextual'), ('irrelevant', 'Irrelevant'), ('duplicate', 'Duplicate'), ('unknown', 'Unknown')], default='unknown', max_length=32)),
                ('usability', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low'), ('reject', 'Reject')], default='low', max_length=16)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], db_index=True, default='active', max_length=16)),
                ('canonical_for_category', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('discovered_layer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manifest_entries', to='gis_registry.gisdiscoveredlayer')),
                ('source_submission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manifest_entries', to='gis_registry.gissourcesubmission')),
            ],
            options={
                'ordering': ['category', 'key'],
                'indexes': [models.Index(fields=['category', 'status'], name='gis_mfst_cat_stat_idx'), models.Index(fields=['source_org'], name='gis_manifest_source_org_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='gisdiscoveredlayer',
            index=models.Index(fields=['layer_url'], name='gis_discovered_layer_url_idx'),
        ),
        migrations.AddIndex(
            model_name='gisdiscoveredlayer',
            index=models.Index(fields=['service_type', 'layer_id'], name='gis_disc_type_id_idx'),
        ),
        migrations.AddConstraint(
            model_name='gisdiscoveredlayer',
            constraint=models.UniqueConstraint(fields=('source_submission', 'layer_url'), name='gis_discovered_layer_submission_layer_unique'),
        ),
    ]
