"""
Django settings for django_project project.

Generated by 'django-admin startproject' using Django 2.2.12.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os
import sys
import netifaces
from pathlib import Path

from config.bootstrap import ensure_config
from dotenv import load_dotenv

BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(BASE_DIR / ".env")

ensure_config()

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'd0644e6ff126cf9ac1b3171a868ae05b'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

# Find out what the IP addresses are at run time
# This is necessary because otherwise Gunicorn will reject the connections
def ip_addresses():
    try:
        interfaces = netifaces.interfaces()
    except PermissionError:
        return ["127.0.0.1", "::1","159.65.103.78","73.239.250.243"]

    ip_list = []
    for interface in interfaces:
        try:
            addrs = netifaces.ifaddresses(interface)
        except PermissionError:
            continue
        for x in (netifaces.AF_INET, netifaces.AF_INET6):
            if x in addrs:
                ip_list.append(addrs[x][0]['addr'])

    return ip_list or ["127.0.0.1", "::1"]

ALLOWED_HOSTS = list(dict.fromkeys(ip_addresses() + ["code.openskagit.com","localhost", "127.0.0.1", "testserver","159.65.103.78","openskagit.com","www.openskagit.com"]))


def _csv_env(name: str):
    raw = os.getenv(name, "")
    if not raw:
        return []
    return [part.strip() for part in raw.split(",") if part.strip()]


def _env_flag(name: str, default: bool = False) -> bool:
    raw = os.getenv(name)
    if raw is None:
        return default
    return raw.strip().lower() in {"1", "true", "yes", "on"}


def _running_under_gevent() -> bool:
    """
    Detect Gunicorn gevent workers so Django ORM can run without tripping
    asyncio safety checks in gevent's event-loop context.
    """
    try:
        from gevent import monkey
    except Exception:
        return False
    return bool(monkey.is_module_patched("socket"))


def _running_under_gunicorn() -> bool:
    argv = " ".join(sys.argv).lower()
    server_software = str(os.environ.get("SERVER_SOFTWARE", "")).lower()
    return "gunicorn" in argv or "gunicorn" in server_software


def _allow_async_unsafe_for_runtime() -> bool:
    """
    Django's async safety check can false-positive under gevent/gunicorn worker
    contexts, even for normal sync views (including /admin). Keep it enabled by
    default, but relax it for this known deployment runtime.
    """
    if _running_under_gevent():
        return True
    if _running_under_gunicorn():
        try:
            import gevent  # noqa: F401
        except Exception:
            return False
        return True
    return False


if _allow_async_unsafe_for_runtime():
    os.environ.setdefault("DJANGO_ALLOW_ASYNC_UNSAFE", "true")


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'planning',
    'openskagit',
    'mcp_agent',
    'rest_framework',
    "django.contrib.gis",
    "leaflet",
    'django.contrib.humanize',
    'django.contrib.postgres',
    'agent',
    'reference_data',
    'gastronet',
    'anymail',
    'django_extensions',
    'legal_code',
    'gis.apps.GisConfig',
]

LEAFLET_CONFIG = {
    "DEFAULT_CENTER": (48.5, -122.3),  # roughly Skagit County
    "DEFAULT_ZOOM": 10,
    "MIN_ZOOM": 5,
    "MAX_ZOOM": 19,
    "SCALE": "metric",
}

CESIUM_ION_TOKEN = os.getenv("CESIUM_API_KEY")

LOG_DIR = BASE_DIR / "logs"
LOG_DIR.mkdir(parents=True, exist_ok=True)

GOOGLE_PLACES_API_KEY = os.getenv("GOOGLE_PLACES_API_KEY", "")
GENAI_API_KEY = os.getenv("GENAI_API_KEY", "")
YOUTUBE_MEETING_GEMINI_MODEL = os.getenv("YOUTUBE_MEETING_GEMINI_MODEL", "gemini-2.0-flash")
OUTSCRAPER_API_KEY = os.getenv("OUTSCRAPER_API_KEY")
OPENAI_API_KEY = os.getenv("OPENAI_API_KEY")
MODAL_IMAGE_APP_NAME = os.getenv("MODAL_IMAGE_APP_NAME", "flux-generator")
MODAL_IMAGE_FUNCTION_NAME = os.getenv("MODAL_IMAGE_FUNCTION_NAME", "generate_image")
MODAL_IMAGE_CLASS_NAME = os.getenv("MODAL_IMAGE_CLASS_NAME", "FluxGenerator")
MODAL_IMAGE_GENERATION_TIMEOUT_SECONDS = int(os.getenv("MODAL_IMAGE_GENERATION_TIMEOUT_SECONDS", "120"))
MODAL_IMAGE_INIT_IMAGE_ENCODING = os.getenv("MODAL_IMAGE_INIT_IMAGE_ENCODING", "bytes")
MODAL_IMAGE_ENVIRONMENT_NAME = os.getenv("MODAL_IMAGE_ENVIRONMENT_NAME", "")
MODAL_IMAGE_JOB_MAX_WORKERS = int(os.getenv("MODAL_IMAGE_JOB_MAX_WORKERS", "1"))
MODAL_IMAGE_POLL_INTERVAL_MS = int(os.getenv("MODAL_IMAGE_POLL_INTERVAL_MS", "2000"))
MODAL_IMAGE_POLL_DB_WORKERS = int(os.getenv("MODAL_IMAGE_POLL_DB_WORKERS", "2"))
MODAL_IMAGE_POLL_DB_TIMEOUT_SECONDS = float(os.getenv("MODAL_IMAGE_POLL_DB_TIMEOUT_SECONDS", "5"))
MODAL_IMAGE_REMOTE_RETRY_COUNT = int(os.getenv("MODAL_IMAGE_REMOTE_RETRY_COUNT", "0"))
MODAL_IMAGE_REMOTE_RETRY_DELAY_SECONDS = float(os.getenv("MODAL_IMAGE_REMOTE_RETRY_DELAY_SECONDS", "1.5"))
REDIS_URL = os.getenv("REDIS_URL", "redis://127.0.0.1:6379/0")
STRIPE_SECRET_KEY = os.getenv("STRIPE_SECRET_KEY", "")
STRIPE_WEBHOOK_SECRET = os.getenv("STRIPE_WEBHOOK_SECRET", "")
STRIPE_PRICE_ID = os.getenv("STRIPE_PRICE_ID", "")
INVESTOR_LEADS_BYPASS_CHECKOUT = _env_flag("INVESTOR_LEADS_BYPASS_CHECKOUT", False)

CELERY_BROKER_URL = REDIS_URL
CELERY_RESULT_BACKEND = REDIS_URL


def _log_file_path(preferred: Path) -> str:
    """
    Ensure the logging path is writable; fall back to /tmp if the preferred location
    cannot be created or opened (e.g., due to ownership/permissions).
    """
    try:
        preferred.parent.mkdir(parents=True, exist_ok=True)
        preferred.touch(exist_ok=True)
        try:
            preferred.chmod(0o664)
        except OSError:
            pass
        return str(preferred)
    except OSError:
        fallback = Path("/tmp") / preferred.name
        fallback.parent.mkdir(parents=True, exist_ok=True)
        fallback.touch(exist_ok=True)
        return str(fallback)


LOG_FILE = _log_file_path(LOG_DIR / "django.log")

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "standard": {
            "format": "%(asctime)s %(levelname)s %(name)s %(message)s",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "standard",
        },
        "null": {
            "class": "logging.NullHandler",
        },
        "file": {
            "class": "logging.handlers.RotatingFileHandler",
            "filename": LOG_FILE,
            "maxBytes": 1024 * 1024 * 5,  # 5 MB
            "backupCount": 5,
            "formatter": "standard",
        },
    },
    "root": {
        "handlers": ["console", "file"],
        "level": "INFO",
    },
    "loggers": {
        "django": {
            "handlers": ["console", "file"],
            "level": "INFO",
            "propagate": False,
        },
        "django.template": {
            "handlers": ["console", "file"],
            "level": "ERROR",
            "propagate": False,
        },
        "django.security.DisallowedHost": {
            "handlers": ["null"],
            "propagate": False,
        },
        "openskagit": {  # your app
            "handlers": ["console", "file"],
            "level": "INFO",
            "propagate": False,
        },
    },
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'agent.views_api.SimpleLoggingMiddleware',
]

ROOT_URLCONF = 'django_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'openskagit.context_processors.primary_nav_links',
            ],
        },
    },
]

WSGI_APPLICATION = 'django_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#dat
if os.environ.get("USE_SQLITE_FOR_TESTS") or ("test" in sys.argv and not os.environ.get("USE_POSTGIS_FOR_TESTS")):
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "test_db.sqlite3",
        }
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.contrib.gis.db.backends.postgis",
            "NAME": os.getenv("DB_NAME"),
            "USER": os.getenv("DB_USER"),
            "PASSWORD": os.getenv("DB_PASSWORD"),
            "HOST": os.getenv("DB_HOST", "127.0.0.1"),
            "PORT": os.getenv("DB_PORT", "5432"),
        }
    }



RESEND_API_KEY = os.getenv("RESEND_API_KEY", "re_8xaofjgX_CySH4hoJVnprbWJD67mN4HGE")
SITE_URL = os.getenv("SITE_URL", "https://openskagit.com")
DEFAULT_FROM_EMAIL = "newsletter@openskagit.com"
EMAIL_BACKEND = "anymail.backends.resend.EmailBackend"
ANYMAIL = {
    "RESEND_API_KEY": RESEND_API_KEY,
}
# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

# URL that serves static files
STATIC_URL = '/static/'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# CO Appraiser parcel route planner (free/open routing defaults)
COAPPRAISER_DEPOT_NAME = os.environ.get("COAPPRAISER_DEPOT_NAME", "Skagit County Assessor (Mount Vernon)")
COAPPRAISER_DEPOT_LAT = float(os.environ.get("COAPPRAISER_DEPOT_LAT", "48.4190"))
COAPPRAISER_DEPOT_LON = float(os.environ.get("COAPPRAISER_DEPOT_LON", "-122.3348"))
COAPPRAISER_ROUTER_BASE_URL = os.environ.get("COAPPRAISER_ROUTER_BASE_URL", "https://router.project-osrm.org")
COAPPRAISER_ROUTER_TIMEOUT_SECONDS = float(os.environ.get("COAPPRAISER_ROUTER_TIMEOUT_SECONDS", "20"))
COAPPRAISER_ROUTER_MAX_COORDS = int(os.environ.get("COAPPRAISER_ROUTER_MAX_COORDS", "100"))
COAPPRAISER_CLUSTER_BACKEND = os.environ.get("COAPPRAISER_CLUSTER_BACKEND", "auto")
COAPPRAISER_SPOPT_MAX_READY_STOPS = int(os.environ.get("COAPPRAISER_SPOPT_MAX_READY_STOPS", "500"))
COAPPRAISER_ASYNC_MIN_READY_STOPS = int(os.environ.get("COAPPRAISER_ASYNC_MIN_READY_STOPS", "450"))

# Directory where 'collectstatic' will put everything
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Directories where Django looks for static assets in apps
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

# Use hashed filenames for static assets in production so browsers
# receive cache-busted URLs whenever assets change.
if not DEBUG:
    STATICFILES_STORAGE = "django.contrib.staticfiles.storage.ManifestStaticFilesStorage"

# Optional cache optimization for production

SESSION_COOKIE_SAMESITE = None
CSRF_COOKIE_SAMESITE = None
SESSION_COOKIE_SECURE = True
CSRF_COOKIE_SECURE = True
# Keep cross-origin requests origin-only so OSM tile requests include a valid
# referrer without leaking full URL paths.
SECURE_REFERRER_POLICY = os.environ.get("SECURE_REFERRER_POLICY", "strict-origin-when-cross-origin")
REST_FRAMEWORK = {
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 25,
    "DEFAULT_RENDERER_CLASSES": [
        "rest_framework.renderers.JSONRenderer",
    ],
}

# Vector search configuration
EMBEDDING_MODEL_NAME = "all-MiniLM-L6-v2"
SERP_API_KEY = "0bd10550fdad36c9024ec6f910559b3c8c2c29e895cd62b894f9816d54b26080"
DIFFBOT_TOKEN = "d8fe54ba8882f217f75307eb2a286d99"
# OpenAI configuration
OPENAI_RESPONSES_MODEL = os.environ.get("OPENAI_RESPONSES_MODEL", "gpt-4o-mini")
OPENAI_SKAGIT_DISH_MODEL = os.environ.get("OPENAI_SKAGIT_DISH_MODEL", "gpt-5-nano")
REPLICATE_API_KEY = os.environ.get("REPLICATE_API_KEY")

# Appeal helper configuration
# Optional JSON with pre-parsed ratio summary; if not present, we attempt a best-effort PDF parse.
RATIO_SUMMARY_JSON = os.environ.get("RATIO_SUMMARY_JSON")
RATIO_SUMMARY_PDF = os.environ.get("RATIO_SUMMARY_PDF") or str(BASE_DIR / "2025-'26 all-county ratio summary.pdf")
